### ISSUE TITLE
What does PPLNN stands for? 

### ISSUE THREAD

**Issue by bluaxe** [openppl-public/ppl.nn#1]
PPLNN, which is short for "PPLNN is a Primitive Library for Neural Network"

The first  P stands for `PPLNN `, the second P stands for Primitive, is it correct?

**Comment by openppl-public** [comment]
> PPLNN, which is short for "PPLNN is a Primitive Library for Neural Network"
> 
> The first P stands for `PPLNN `, the second P stands for Primitive, is it correct?

you got it

**Comment by zhaoxuejun1234** [comment]
Parrots Primitive Library Neural Network

**Comment by Jack47** [comment]
> Parrots Primitive Library Neural Network

so when will Parrots open source?

**Comment by zhaoxuejun1234** [comment]
Sorry,pal, I don't know. For me, op matters

**Comment by shuo-ouyang** [comment]
The name style of PPLNN is similar with GNU (GNU is Not Unix) and PHP (PHP: Hypertext Preprocessor).
