### ISSUE TITLE
Why sample model tests/testdata/conv.onnx  CANNOT be profiled ?

### ISSUE THREAD

**Issue by codgeek** [openppl-public/ppl.nn#10]
I build ppl.nn project, and try one test by `./pplnn-build/tools/pplnn --onnx-model tests/testdata/conv.onnx`， it works normally,
```
[INFO][2021-07-05 21:47:39.764][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8-dirty
[INFO][2021-07-05 21:47:39.764][pplnn.cc:110] ***** register X86Engine *****
[INFO][2021-07-05 21:47:39.764][simple_graph_partitioner.cc:90] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2021-07-05 21:47:39.764][pplnn.cc:523] ----- input info -----
[INFO][2021-07-05 21:47:39.764][pplnn.cc:526] input[0]:
[INFO][2021-07-05 21:47:39.764][pplnn.cc:527]     name: input
[INFO][2021-07-05 21:47:39.764][pplnn.cc:534]     dim(s): 1 3 4 4
[INFO][2021-07-05 21:47:39.764][pplnn.cc:536]     DataType: FLOAT32
[INFO][2021-07-05 21:47:39.764][pplnn.cc:537]     DataFormat: NDARRAY
[INFO][2021-07-05 21:47:39.764][pplnn.cc:538]     NumBytesIncludePadding: 192
[INFO][2021-07-05 21:47:39.764][pplnn.cc:539]     NumBytesExcludePadding: 192
[INFO][2021-07-05 21:47:39.764][pplnn.cc:542] ----- output info -----
[INFO][2021-07-05 21:47:39.764][pplnn.cc:545] output[0]:
[INFO][2021-07-05 21:47:39.764][pplnn.cc:546]     name: 5
[INFO][2021-07-05 21:47:39.764][pplnn.cc:553]     dim(s): 1 3 5 5
[INFO][2021-07-05 21:47:39.764][pplnn.cc:555]     DataType: FLOAT32
[INFO][2021-07-05 21:47:39.764][pplnn.cc:556]     DataFormat: N16CX
[INFO][2021-07-05 21:47:39.764][pplnn.cc:557]     NumBytesIncludePadding: 1600
[INFO][2021-07-05 21:47:39.764][pplnn.cc:558]     NumBytesExcludePadding: 300
[INFO][2021-07-05 21:47:39.764][pplnn.cc:561] ----------------------
[INFO][2021-07-05 21:47:39.764][pplnn.cc:791] Run() costs: 0.010000 ms.
[INFO][2021-07-05 21:47:39.764][pplnn.cc:799] Run ok
```

when I try to run in profile mode, It got stuck at some where and never return. 😅😅 code it too new to me, hard to find  cause, pls help~ 

comand: `./pplnn-build/tools/pplnn --onnx-model tests/testdata/conv.onnx  --enable-profiling --warmuptimes  3`
```
[INFO][2021-07-05 21:52:35.459][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8-dirty
[INFO][2021-07-05 21:52:35.459][pplnn.cc:110] ***** register X86Engine *****
[INFO][2021-07-05 21:52:35.459][simple_graph_partitioner.cc:90] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2021-07-05 21:52:35.459][pplnn.cc:523] ----- input info -----
[INFO][2021-07-05 21:52:35.459][pplnn.cc:526] input[0]:
[INFO][2021-07-05 21:52:35.459][pplnn.cc:527]     name: input
[INFO][2021-07-05 21:52:35.459][pplnn.cc:534]     dim(s): 1 3 4 4
[INFO][2021-07-05 21:52:35.459][pplnn.cc:536]     DataType: FLOAT32
[INFO][2021-07-05 21:52:35.459][pplnn.cc:537]     DataFormat: NDARRAY
[INFO][2021-07-05 21:52:35.459][pplnn.cc:538]     NumBytesIncludePadding: 192
[INFO][2021-07-05 21:52:35.459][pplnn.cc:539]     NumBytesExcludePadding: 192
[INFO][2021-07-05 21:52:35.459][pplnn.cc:542] ----- output info -----
[INFO][2021-07-05 21:52:35.459][pplnn.cc:545] output[0]:
[INFO][2021-07-05 21:52:35.459][pplnn.cc:546]     name: 5
[INFO][2021-07-05 21:52:35.459][pplnn.cc:553]     dim(s): 1 3 5 5
[INFO][2021-07-05 21:52:35.459][pplnn.cc:555]     DataType: FLOAT32
[INFO][2021-07-05 21:52:35.459][pplnn.cc:556]     DataFormat: N16CX
[INFO][2021-07-05 21:52:35.459][pplnn.cc:557]     NumBytesIncludePadding: 1600
[INFO][2021-07-05 21:52:35.459][pplnn.cc:558]     NumBytesExcludePadding: 300
[INFO][2021-07-05 21:52:35.459][pplnn.cc:561] ----------------------
[INFO][2021-07-05 21:52:35.459][pplnn.cc:791] Run() costs: 0.010000 ms.
[INFO][2021-07-05 21:52:35.459][pplnn.cc:799] Run ok
[INFO][2021-07-05 21:52:35.459][pplnn.cc:803] Warm up start for 3 times.
[INFO][2021-07-05 21:52:35.459][pplnn.cc:810] Warm up end.
[INFO][2021-07-05 21:52:35.459][pplnn.cc:818] Profiling start
```

**Comment by ltj2013** [comment]
You can enable the profiling flag in CMakeLists.
https://github.com/openppl-public/ppl.nn/blob/513e6122dd90f619da0e550a8a3dc5e3184e5c58/CMakeLists.txt#L11

**Comment by ltj2013** [comment]
You can enable the profiling flag in CMakeLists.
https://github.com/openppl-public/ppl.nn/blob/513e6122dd90f619da0e550a8a3dc5e3184e5c58/CMakeLists.txt#L11

**Comment by codgeek** [comment]
> You can enable the profiling flag in CMakeLists.
> https://github.com/openppl-public/ppl.nn/blob/513e6122dd90f619da0e550a8a3dc5e3184e5c58/CMakeLists.txt#L11

seems not work by this flag.  this test model conv.onnx  still got stuck.

```
-options="-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${pplnn_build_dir}/install $*"
+options="-DCMAKE_BUILD_TYPE=Release -DPPLNN_ENABLE_KERNEL_PROFILING=ON -DCMAKE_INSTALL_PREFIX=${pplnn_build_dir}/install $*"
```

```
tests/testdata/conv.onnx  --enable-profiling --warmuptimes 3
[INFO][2021-07-05 22:19:38.555][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58-dirty
[INFO][2021-07-05 22:19:38.555][pplnn.cc:127] ***** register X86Engine *****
[INFO][2021-07-05 22:19:38.555][simple_graph_partitioner.cc:107] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2021-07-05 22:19:38.555][pplnn.cc:540] ----- input info -----
[INFO][2021-07-05 22:19:38.555][pplnn.cc:543] input[0]:
[INFO][2021-07-05 22:19:38.555][pplnn.cc:544]     name: input
[INFO][2021-07-05 22:19:38.555][pplnn.cc:551]     dim(s): 1 3 4 4
[INFO][2021-07-05 22:19:38.555][pplnn.cc:553]     DataType: FLOAT32
[INFO][2021-07-05 22:19:38.555][pplnn.cc:554]     DataFormat: NDARRAY
[INFO][2021-07-05 22:19:38.555][pplnn.cc:555]     NumBytesIncludePadding: 192
[INFO][2021-07-05 22:19:38.555][pplnn.cc:556]     NumBytesExcludePadding: 192
[INFO][2021-07-05 22:19:38.555][pplnn.cc:559] ----- output info -----
[INFO][2021-07-05 22:19:38.555][pplnn.cc:562] output[0]:
[INFO][2021-07-05 22:19:38.556][pplnn.cc:563]     name: 5
[INFO][2021-07-05 22:19:38.556][pplnn.cc:570]     dim(s): 1 3 5 5
[INFO][2021-07-05 22:19:38.556][pplnn.cc:572]     DataType: FLOAT32
[INFO][2021-07-05 22:19:38.556][pplnn.cc:573]     DataFormat: N16CX
[INFO][2021-07-05 22:19:38.556][pplnn.cc:574]     NumBytesIncludePadding: 1600
[INFO][2021-07-05 22:19:38.556][pplnn.cc:575]     NumBytesExcludePadding: 300
[INFO][2021-07-05 22:19:38.556][pplnn.cc:578] ----------------------
[INFO][2021-07-05 22:19:38.556][pplnn.cc:808] Run() costs: 0.010000 ms.
[INFO][2021-07-05 22:19:38.556][pplnn.cc:816] Run ok
[INFO][2021-07-05 22:19:38.556][pplnn.cc:820] Warm up start for 3 times.
[INFO][2021-07-05 22:19:38.556][pplnn.cc:827] Warm up end.
[INFO][2021-07-05 22:19:38.556][pplnn.cc:835] Profiling start
```

**Comment by codgeek** [comment]
> > comand: `./pplnn-build/tools/pplnn --onnx-model tests/testdata/conv.onnx --enable-profiling --warmuptimes 3`
> 
> I tried this command and it worked correctly in my machine. Cound you delete the `pplnn-build` directory and re-run the build command `./build.sh` and try the command above again?

I've tried, tests/testdata/conv.onnx still got stuck.

Occasionally i tried another mobileNetV2 model,  Profiling run to the end. It seems the conv.onnx sample has something wrong 
```
[INFO][2021-07-05 22:29:08.104][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58-dirty
[INFO][2021-07-05 22:29:08.104][pplnn.cc:127] ***** register X86Engine *****
[INFO][2021-07-05 22:29:08.116][simple_graph_partitioner.cc:107] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2021-07-05 22:29:08.139][pplnn.cc:540] ----- input info -----
[INFO][2021-07-05 22:29:08.139][pplnn.cc:543] input[0]:
[INFO][2021-07-05 22:29:08.139][pplnn.cc:544]     name: input
[INFO][2021-07-05 22:29:08.139][pplnn.cc:551]     dim(s): 1 3 224 224
[INFO][2021-07-05 22:29:08.139][pplnn.cc:553]     DataType: FLOAT32
[INFO][2021-07-05 22:29:08.139][pplnn.cc:554]     DataFormat: NDARRAY
[INFO][2021-07-05 22:29:08.139][pplnn.cc:555]     NumBytesIncludePadding: 602112
[INFO][2021-07-05 22:29:08.139][pplnn.cc:556]     NumBytesExcludePadding: 602112
[INFO][2021-07-05 22:29:08.139][pplnn.cc:559] ----- output info -----
[INFO][2021-07-05 22:29:08.139][pplnn.cc:562] output[0]:
[INFO][2021-07-05 22:29:08.139][pplnn.cc:563]     name: output
[INFO][2021-07-05 22:29:08.139][pplnn.cc:570]     dim(s): 1 1000
[INFO][2021-07-05 22:29:08.139][pplnn.cc:572]     DataType: FLOAT32
[INFO][2021-07-05 22:29:08.139][pplnn.cc:573]     DataFormat: NDARRAY
[INFO][2021-07-05 22:29:08.139][pplnn.cc:574]     NumBytesIncludePadding: 4000
[INFO][2021-07-05 22:29:08.139][pplnn.cc:575]     NumBytesExcludePadding: 4000
[INFO][2021-07-05 22:29:08.139][pplnn.cc:578] ----------------------
[INFO][2021-07-05 22:29:08.139][pplnn.cc:808] Run() costs: 9.195000 ms.
[INFO][2021-07-05 22:29:08.139][pplnn.cc:816] Run ok
[INFO][2021-07-05 22:29:08.139][pplnn.cc:820] Warm up start for 3 times.
[INFO][2021-07-05 22:29:08.161][pplnn.cc:827] Warm up end.
[INFO][2021-07-05 22:29:08.161][pplnn.cc:835] Profiling start
[INFO][2021-07-05 22:29:09.164][pplnn.cc:851] Duration: 1002.473000 ms
[INFO][2021-07-05 22:29:09.164][pplnn.cc:861] Average run cost: 7.317321 ms.
[INFO][2021-07-05 22:29:09.164][pplnn.cc:864] Profiling End
```

**Comment by codgeek** [comment]
> You can enable the profiling flag in CMakeLists.
> https://github.com/openppl-public/ppl.nn/blob/513e6122dd90f619da0e550a8a3dc5e3184e5c58/CMakeLists.txt#L11

Actually, I tried and find this `PPLNN_ENABLE_KERNEL_PROFILING ` macro is designed for exporting detailed timing for each op,  other than the profiling of just run multi loops,   the `--enable-profiling `  is corresponding to the second kind.

**Comment by ltj2013** [comment]
> > You can enable the profiling flag in CMakeLists.
> > https://github.com/openppl-public/ppl.nn/blob/513e6122dd90f619da0e550a8a3dc5e3184e5c58/CMakeLists.txt#L11
> 
> Actually, I tried and find this `PPLNN_ENABLE_KERNEL_PROFILING ` macro is designed for exporting detailed timing for each op, other than the profiling of just run multi loops, the `--enable-profiling ` is corresponding to the second kind.

Yes, PPLNN_ENABLE_KERNEL_PROFILING macro is designed for exporting detailed timing for each op. And --enable-profiling is also used to print the kernel profiling in detail.

**Comment by Alcanderian** [comment]
Oh, our bad I think. 😅😅
Simple conv may cost too little time for accumulating the double value, but I am not sure.
We are going to find out why it sticks there.

**Comment by Alcanderian** [comment]
> > > comand: `./pplnn-build/tools/pplnn --onnx-model tests/testdata/conv.onnx --enable-profiling --warmuptimes 3`
> > 
> > 
> > I tried this command and it worked correctly in my machine. Cound you delete the `pplnn-build` directory and re-run the build command `./build.sh` and try the command above again?
> 
> I've tried, tests/testdata/conv.onnx still got stuck.
> 
> Occasionally i tried another mobileNetV2 model, Profiling run to the end. It seems the conv.onnx sample has something wrong
> 
> ```
> [INFO][2021-07-05 22:29:08.104][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58-dirty
> [INFO][2021-07-05 22:29:08.104][pplnn.cc:127] ***** register X86Engine *****
> [INFO][2021-07-05 22:29:08.116][simple_graph_partitioner.cc:107] total partition(s) of graph[torch-jit-export]: 1.
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:540] ----- input info -----
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:543] input[0]:
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:544]     name: input
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:551]     dim(s): 1 3 224 224
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:553]     DataType: FLOAT32
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:554]     DataFormat: NDARRAY
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:555]     NumBytesIncludePadding: 602112
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:556]     NumBytesExcludePadding: 602112
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:559] ----- output info -----
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:562] output[0]:
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:563]     name: output
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:570]     dim(s): 1 1000
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:572]     DataType: FLOAT32
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:573]     DataFormat: NDARRAY
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:574]     NumBytesIncludePadding: 4000
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:575]     NumBytesExcludePadding: 4000
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:578] ----------------------
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:808] Run() costs: 9.195000 ms.
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:816] Run ok
> [INFO][2021-07-05 22:29:08.139][pplnn.cc:820] Warm up start for 3 times.
> [INFO][2021-07-05 22:29:08.161][pplnn.cc:827] Warm up end.
> [INFO][2021-07-05 22:29:08.161][pplnn.cc:835] Profiling start
> [INFO][2021-07-05 22:29:09.164][pplnn.cc:851] Duration: 1002.473000 ms
> [INFO][2021-07-05 22:29:09.164][pplnn.cc:861] Average run cost: 7.317321 ms.
> [INFO][2021-07-05 22:29:09.164][pplnn.cc:864] Profiling End
> ```

I've tried simple conv on my machine. I found it will take about 10 seconds to finish the profiling because it take tooooooooooooooo little time in each run, lmao.
You will find the time is slowly growing if you print the `run_dur` at pplnn.cc:847, just be patient:)
