### ISSUE TITLE
shape support of BatchNorm

### ISSUE THREAD

**Issue by OneMoreSecond** [openppl-public/ppl.nn#106]
Current BatchNorm implementation only supports 4-dim inputs, while ONNX operator specification supports 2-dim inputs.
Is it by design?

https://github.com/openppl-public/ppl.nn/blob/75af6eedf96aa0bcd07941db668a9c172a2e3478/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/batchnorm/batchnorm_normal_fp32_avx.cpp

I fixed it locally like https://github.com/openppl-public/ppl.nn/pull/108, which works for my scenario.

**Comment by Alcanderian** [comment]
Thanks for the feedback.

There some oversights in the implement of batchnorm.
The dimensions of input should consider to be any, we will fix it ASAP.

You can use your local fix temporarily, but I cannot accept this MR. There are more codes should be fix, sorry.

**Comment by Alcanderian** [comment]
Hi, here
#110 has expand batchnorm acceptable dims form 4 to any.
You can check if it works before it has been merged

**Comment by OneMoreSecond** [comment]
I have tested it. It works well. Thanks!
