### ISSUE TITLE
[x86-compile] error: impossible constraint in ‘asm’

### ISSUE THREAD

**Issue by alanzhai219** [openppl-public/ppl.nn#111]
I try to compile the latest master.

CPU | result
------- | -------------
Core i5-9500(not support avx512) | `error: impossible constraint in ‘asm’`
Xeon 6130(support avx512)             |  pass

I find that latest commit supports AVX-512. If it is a bug, will ppl support more CPU(no avx512) and any macro to separate AVX-512 codes?
Thanks.

**Comment by alanzhai219** [comment]
e7176cf33cdc1eda42ec30eafe8cd6bda3a78ad9 causes such error. inline code cant work properly in some CPU.

**Comment by Alcanderian** [comment]
This error is not about the CPU but the compiler.
Can you tell us about your environment? 
Including OS, compiler and the command-line?

**Comment by alanzhai219** [comment]
> You can append `-DPPL_USE_X86_AVX512=OFF` to the cmake command-line to separate the AVX512 codes.
> But in this case, the error is not about the CPU but the compiler.
> Can you tell us about your environment?
> Including OS, compiler and the command-line?

os : ubuntu20.04
gcc: 9.3.0

**Comment by Alcanderian** [comment]
> os : ubuntu20.04
gcc: 9.3.0
cmd: ./build.sh -DHPCC_USE_X86_64=ON

I cannot reproduce the compile error with a similar environment.
I have built the lastest master successfully with:
CPU: i7-10700K
OS: ubuntu 20.04.2
gcc: 9.3.0
cmd: ./build.sh -DHPCC_USE_X86_64=ON

Can you show the entire error message by GCC?

**Comment by alanzhai219** [comment]
> > os : ubuntu20.04
> > gcc: 9.3.0
> > cmd: ./build.sh -DHPCC_USE_X86_64=ON
> 
> I cannot reproduce the compile error with a similar environment.
> I have built the lastest master successfully with:
> CPU: i7-10700K
> OS: ubuntu 20.04.2
> gcc: 9.3.0
> cmd: ./build.sh -DHPCC_USE_X86_64=ON
> 
> Can you show the entire error message by GCC?
/home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp: In function ‘void ppl::kernel::x86::gemm_fp32_fma_kernel_core(int64_t*) [with long int u_m = 1; long int u_n = 8]’:
/home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: warning: asm operand 4 probably doesn’t match constraints
  321 |     );
      |      ^
/home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: error: impossible constraint in ‘asm’
/home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp: In function ‘void ppl::kernel::x86::gemm_fp32_fma_kernel_core(int64_t*) [with long int u_m = 2; long int u_n = 8]’:
/home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: warning: asm operand 4 probably doesn’t match constraints
  321 |     );

**Comment by Alcanderian** [comment]
> > > os : ubuntu20.04
> > > gcc: 9.3.0
> > > cmd: ./build.sh -DHPCC_USE_X86_64=ON
> > 
> > 
> > I cannot reproduce the compile error with a similar environment.
> > I have built the lastest master successfully with:
> > CPU: i7-10700K
> > OS: ubuntu 20.04.2
> > gcc: 9.3.0
> > cmd: ./build.sh -DHPCC_USE_X86_64=ON
> > Can you show the entire error message by GCC?
> 
> Hope it is not late to say sorry. I think my description above may guides wrong direction.
> In brief, try to replace 'Release' with 'Debug' in build.sh and then rebuild your master.
> 
> ```shell
> /home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp: In function ‘void ppl::kernel::x86::gemm_fp32_fma_kernel_core(int64_t*) [with long int u_m = 1; long int u_n = 8]’:
> /home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: warning: asm operand 4 probably doesn’t match constraints
>   321 |     );
>       |      ^
> /home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: error: impossible constraint in ‘asm’
> /home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp: In function ‘void ppl::kernel::x86::gemm_fp32_fma_kernel_core(int64_t*) [with long int u_m = 2; long int u_n = 8]’:
> /home/workspace/ppl.nn/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp:321:6: warning: asm operand 4 probably doesn’t match constraints
>   321 |     );
> ```

Hello, I fix the compile issue with bulid type `Debug` in #109 .
You can try my forked repo first or wait for the manager to accept the merge request.

**Comment by alanzhai219** [comment]
LGTM
