### ISSUE TITLE
WSL complie error: failed to convert GOTPCREL relocation; relink with --no-relax

### ISSUE THREAD

**Issue by szh6** [openppl-public/ppl.nn#113]
I want to complie the classification model under the path: ppl.nn/pplnn-build/samples/cpp/run_model, but get this issue.
the complie log is :
`
[  1%] Built target pplcommon_static
Consolidate compiler generated dependencies of target PPLCUDAKernel
[ 10%] Built target PPLCUDAKernel
[ 18%] Built target libprotobuf
[ 43%] Built target PPLKernelX86
Consolidate compiler generated dependencies of target pplnn_static
[100%] Built target pplnn_static
Consolidate compiler generated dependencies of target classification
[100%] Linking CXX executable classification
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
samples/cpp/run_model/CMakeFiles/classification.dir/build.make:150: recipe for target 'samples/cpp/run_model/classification' failed
make[2]: *** [samples/cpp/run_model/classification] Error 1
CMakeFiles/Makefile2:1040: recipe for target 'samples/cpp/run_model/CMakeFiles/classification.dir/all' failed
make[1]: *** [samples/cpp/run_model/CMakeFiles/classification.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

`
my cuda version is 11.0

**Comment by ouonline** [comment]
what's the command you used?

**Comment by szh6** [comment]
> what's the command you used?

1.First I use **./build.sh -DHPCC_USE_X86_64=ON -DHPCC_USE_CUDA=ON** command to build CUDA engine and x86_64 engine. At the end of building, the problem as I mentioned above occured.
2. Then I try to build again under the path (ppl.nn/pplnn-build/samples/cpp/run_model) with the command **make**, the same error still existed.

**Comment by szh6** [comment]
BTW, is the command parameter **--runningtimes** invalid ? I want to test the average comsuing time of model after running  multiple times. How can I test it ?

**Comment by ouonline** [comment]
> > what's the command you used?
> 
> 1.First I use **./build.sh -DHPCC_USE_X86_64=ON -DHPCC_USE_CUDA=ON** command to build CUDA engine and x86_64 engine. At the end of building, the problem as I mentioned above occured.
> 2. Then I try to build again under the path (ppl.nn/pplnn-build/samples/cpp/run_model) with the command **make**, the same error still existed.

I built ppl.nn in WSL of win10 1809 with CUDA 11.1 and it worked well. Maybe you can upgrade CUDA toolkit to 11.1 and try again.

BTW, Windows is not well tested. It is recommended to run ppl.nn on a native Linux OS.

**Comment by szh6** [comment]
> > BTW, is the command parameter **--runningtimes** invalid ? I want to test the average comsuing time of model after running multiple times. How can I test it ?
> 
> Please refer to https://github.com/openppl-public/ppl.nn/blob/master/docs/en/cuda-doc/benchmark_tool.md for CUDA benchmarking details.

Thanks. I get it.
