### ISSUE TITLE
[Improvement] print run time on average single inference

### ISSUE THREAD

**Issue by zerollzeng** [openppl-public/ppl.nn#12]
Hi folks, just a suggestion here:
in https://github.com/openppl-public/ppl.nn/blob/master/docs/en/cuda-doc/benchmark_tool.md

```
The running cost is shown in log as following:

Run() costs: *** ms.
The average running time for once reasoning is running cost divided by the number of running times you set.
```

it's kind of confusing, so I think it would be better to print the average running time directly.

Thanks

**Comment by openppl-public** [comment]
> Hi folks, just a suggestion here:
> in https://github.com/openppl-public/ppl.nn/blob/master/docs/en/cuda-doc/benchmark_tool.md
> 
> ```
> The running cost is shown in log as following:
> 
> Run() costs: *** ms.
> The average running time for once reasoning is running cost divided by the number of running times you set.
> ```
> 
> it's kind of confusing, so I think it would be better to print the average running time directly.
> 
> Thanks

Try to add `--enable-profiling` (and `--min-profiling-time` if needed) when running tools/pplnn.

```bash
./pplnn-build/tools/pplnn --help
```

to see available options.
