### ISSUE TITLE
PPL is not support your GPU device right now

### ISSUE THREAD

**Issue by chensusu11** [openppl-public/ppl.nn#128]
[INFO][2021-09-28 03:27:34.466][simple_graph_partitioner.cc:107] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2021-09-28 03:27:34.466][opt_graph.cc:202] Create 4 TensorImpl
[INFO][2021-09-28 03:27:34.466][opt_graph.cc:313] added 4 new bridge kernels
[ERROR][2021-09-28 03:27:34.467][opt_graph.cc:472] PPL is not support your GPU device right now.
[ERROR][2021-09-28 03:27:34.467][opt_graph.cc:630] Selec algos for each kernel failed: unsupported
[ERROR][2021-09-28 03:27:34.467][engine.cc:58] OptGraph DoOptimeize failed: unsupported
[ERROR][2021-09-28 03:27:34.467][engine.cc:68] DoOptimize failed: unsupported
[ERROR][2021-09-28 03:27:34.467][utils.cc:257] process graph[torch-jit-export] by engine[cuda] failed: unsupported
[ERROR][2021-09-28 03:27:34.467][utils.cc:467] GenPartitionsInfo failed:unsupported
[ERROR][2021-09-28 03:27:34.467][runtime_builder_impl.cc:51] process graph failed: unsupported
[ERROR][2021-09-28 03:27:34.467][onnx_runtime_builder_factory.cc:58] init RuntimeBuilder failed: unsupported
ERROR: create RuntimeBuilder failed.

**Comment by chensusu11** [comment]
请问为什么 PPL 不支持我的GPU device哇

**Comment by ouonline** [comment]
> 请问为什么 PPL 不支持我的GPU device哇

参考这个文档：https://github.com/openppl-public/ppl.nn/blob/master/docs/en/supported-ops-and-platforms.md
