### ISSUE TITLE
git建议

### ISSUE THREAD

**Issue by luuuyi** [openppl-public/ppl.nn#129]
提个建议，能不能把build过程中在线git clone hpcc的方式改成离线的，目前这种方式对断网的内网环境有点不太友好

**Comment by ouonline** [comment]
> 提个建议，能不能把build过程中在线git clone hpcc的方式改成离线的，目前这种方式对断网的内网环境有点不太友好

如果是无法连外网，那么需要手动把依赖都提前下下来；或者找一台有网络环境的机器，编译成功后把 deps 目录拷过去。
