### ISSUE TITLE
mmdetection model Faster_rcnn failed with pplnn 

### ISSUE THREAD

**Issue by Maosquerade** [openppl-public/ppl.nn#13]
I followed the document of converting model with openmmp and generated pretrained faster_rcnn model , but when I used x86 pplnn to run this model, there is an error says:
```
[INFO][2021-07-06 08:48:49.498][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8-dirty
[INFO][2021-07-06 08:48:49.498][pplnn.cc:110] ***** register X86Engine *****
[INFO][2021-07-06 08:48:49.761][simple_graph_partitioner.cc:90] total partition(s) of graph[torch-jit-export]: 1.
[ERROR][2021-07-06 08:48:50.556][kernel.cc:14] reshape kernel[Expand_1100] failed: invalid value
[ERROR][2021-07-06 08:48:50.556][kernel.cc:47] BeforeExecute() of kernel[Expand_1100] failed: invalid value
[ERROR][2021-07-06 08:48:50.556][scheduler_common.cc:153] exec kernel[Expand_1100] failed: invalid value
[ERROR][2021-07-06 08:48:50.556][sequential_scheduler.cc:99] execute kernel[Expand_1100] failed: invalid value
[ERROR][2021-07-06 08:48:50.556][pplnn.cc:784] Run() failed: invalid value
```
The mobilenet can execute successfully. Can I do anything to make this model execute right?

**Comment by openppl-public** [comment]
> I followed the document of converting model with openmmp and generated pretrained faster_rcnn model , but when I used x86 pplnn to run this model, there is an error says:
> 
> ```
> [INFO][2021-07-06 08:48:49.498][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8-dirty
> [INFO][2021-07-06 08:48:49.498][pplnn.cc:110] ***** register X86Engine *****
> [INFO][2021-07-06 08:48:49.761][simple_graph_partitioner.cc:90] total partition(s) of graph[torch-jit-export]: 1.
> [ERROR][2021-07-06 08:48:50.556][kernel.cc:14] reshape kernel[Expand_1100] failed: invalid value
> [ERROR][2021-07-06 08:48:50.556][kernel.cc:47] BeforeExecute() of kernel[Expand_1100] failed: invalid value
> [ERROR][2021-07-06 08:48:50.556][scheduler_common.cc:153] exec kernel[Expand_1100] failed: invalid value
> [ERROR][2021-07-06 08:48:50.556][sequential_scheduler.cc:99] execute kernel[Expand_1100] failed: invalid value
> [ERROR][2021-07-06 08:48:50.556][pplnn.cc:784] Run() failed: invalid value
> ```
> 
> The mobilenet can execute successfully. Can I do anything to make this model execute right?

Can you post the command sequence that are used to convert the faster-rcnn model?

**Comment by Maosquerade** [comment]
My command is just as the insturction of your `model-convert-guide` , the `Example: Converting Faster R-CNN` :
```
cd mmdetection && mkdir checkpoints && cd checkpoints
wget https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

python ../tools/deployment/pytorch2onnx.py ../configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
--output-file faster_rcnn.onnx --simplify --dynamic-export
```

**Comment by openppl-public** [comment]
> My command is just as the insturction of your `model-convert-guide` , the `Example: Converting Faster R-CNN` :
> 
> ```
> cd mmdetection && mkdir checkpoints && cd checkpoints
> wget https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
> 
> python ../tools/deployment/pytorch2onnx.py ../configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
> faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
> --output-file faster_rcnn.onnx --simplify --dynamic-export
> ```

We cannot reproduce your problem. Can you send your converted model to openppl.ai@hotmail.com?

**Comment by Maosquerade** [comment]
Thanks for relpying! I have sent the model and my environment to your email.

**Comment by ZichenTian** [comment]
> Thanks for relpying! I have sent the model and my environment to your email.

We have successfully reproduced your problem on your model. The bug has been fixed and I create a PR:

**Comment by Maosquerade** [comment]
That worked! Thanks a lot!
