### ISSUE TITLE
按官方的mask_rcnn sample执行出错

### ISSUE THREAD

**Issue by luuuyi** [openppl-public/ppl.nn#134]
如题，
mmdetection转mask_rcnn.onnx一切正常，然后使用ppl的python sample推理mask_rcnn模型时报错

`[less_kernel.cc:81] unsupported data_type: FLOAT64`

简单调试了一下，输入数据是fp32的，难道是转出来的onnx是float64？但是官方不是跑通了的么

**Comment by luuuyi** [comment]
基本定位出问题是mask_rcnn从mmdet导出到onnx的时候，fcn_mask_head里面有一个逻辑是让特征图和阈值0.5去比较然后输出mask，在pytorch代码里面全程都是用torch.float和python原生float去做逻辑大小判断，但是通过onnx导出的时候我看了下log，他会把tensor转换为double类型的数据，然后那个0.5的阈值也不再是float32的了，直接就变成了double类型。
这个问题挺奇怪的，int类型的数据做这个逻辑判断的时候，onnx导出也会把tensor转为long类型，然后另一个待比较的值也是会变成long类型，哪怕在mmdet代码里面他们都是int32形式的。

**Comment by luuuyi** [comment]
看了下export onnx的log，硬编码把double类型改掉了

**Comment by pranerd** [comment]
请问下这个最终怎么解决了的了？

**Comment by zhenglongjiepheonix** [comment]
> 请问下这个最终怎么解决了的了？
建议用onnx强行改掉数据的datatype, tensor和原生类型混合导出的时候确实存在inconsistent datatype的问题，可以看一下这个[issue](https://github.com/pytorch/pytorch/issues/20941)
