### ISSUE TITLE
compile error on Mac os

### ISSUE THREAD

**Issue by tangcisi** [openppl-public/ppl.nn#14]
clang = 12.0
when running build.sh, errors occur.
`-- Configuring done

-- Generating done

-- Build files have been written to: /Users/bytedance/Desktop/ppl.nn/pplnn-build

  1 #!/bin/bash

Scanning dependencies of target pplcommon_static

  1 cmake_minimum_required(VERSION 3.11)

Consolidate compiler generated dependencies of target pplcommon_static

[  1%] Building CXX object ppl.common-build/CMakeFiles/pplcommon_static.dir/src/ppl/common/log.cc.o

In file included from /Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:1:

/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.h:54:17: error: class member cannot be redeclared
    LogMessage& operator<<(long long ll);
                ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.h:51:17: note: previous declaration is here
    LogMessage& operator<<(int64_t i64);
                ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.h:55:17: error: class member cannot be redeclared
    LogMessage& operator<<(unsigned long long ull);
                ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.h:52:17: note: previous declaration is here
    LogMessage& operator<<(uint64_t u64);
                ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:75:1: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
DEF_READ_OPERATOR_FUNC(int64_t, "%ld");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 %lld
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:61:44: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
        auto len = snprintf(buf, 128, fmt, value);   \
                                      ~~~  ^~~~~
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:76:1: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
DEF_READ_OPERATOR_FUNC(uint64_t, "%lu");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  %llu
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:61:44: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
        auto len = snprintf(buf, 128, fmt, value);   \
                                      ~~~  ^~~~~
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:78:1: error: redefinition of 'operator<<'
DEF_READ_OPERATOR_FUNC(long long, "%lld");
^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:59:29: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
    LogMessage& LogMessage::operator<<(Type value) { \
                            ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:75:1: note: previous definition is here
DEF_READ_OPERATOR_FUNC(int64_t, "%ld");
^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:59:29: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
    LogMessage& LogMessage::operator<<(Type value) { \
                            ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:79:1: error: redefinition of 'operator<<'
DEF_READ_OPERATOR_FUNC(unsigned long long, "%llu");
^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:59:29: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
    LogMessage& LogMessage::operator<<(Type value) { \
                            ^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:76:1: note: previous definition is here
DEF_READ_OPERATOR_FUNC(uint64_t, "%lu");
^
/Users/bytedance/Desktop/ppl.nn/deps/ppl.common/src/ppl/common/log.cc:59:29: note: expanded from macro 'DEF_READ_OPERATOR_FUNC'
    LogMessage& LogMessage::operator<<(Type value) { \
                            ^
2 warnings and 4 errors generated.
make[2]: *** [ppl.common-build/CMakeFiles/pplcommon_static.dir/src/ppl/common/log.cc.o] Error 1
make[1]: *** [ppl.common-build/CMakeFiles/pplcommon_static.dir/all] Error 2
make: *** [all] Error 2`
Should I delete all the redeclared class member?

**Comment by openppl-public** [comment]
Mac is not supported now.

Reference: https://github.com/openppl-public/ppl.nn/blob/master/docs/en/supported-ops-and-platforms.md
