### ISSUE TITLE
The inference performance of pplnn seems inconsistent for the same model

### ISSUE THREAD

**Issue by shuo-ouyang** [openppl-public/ppl.nn#16]
Hi guys! I used `pplnn` to test inference performance for resnet50 model, but I got definitely different results when I performed `pplnn` five times consecutively. The average latency of a single query ranges from 0.37ms to 2.03ms, which is unexpected and makes me confused.

Device: RTX 3090
CUDA: 11.1
Command:
```
pplnn --warmuptimes 100 --runningtimes 100 --enable-profiling --dims 1_3_224_224 --in-shapes 1_3_224_224 --onnx-model model.onnx
```
Logs:
[resnet50 result](https://paste.ubuntu.com/p/hdgG8TRr5t/)

**Comment by Si-XU** [comment]
When we test performance, we normally set warmuptimes as 400 times. You can take a try.

**Comment by shuo-ouyang** [comment]
@Si-XU Thanks for your response. But I still suffers this problem after increase warmuptimes to 400...

**Comment by Si-XU** [comment]
Cause we donot have RTX 3090. I run several times on T4. The results is stable.

![image](https://user-images.githubusercontent.com/61867914/124893418-4b73a980-e00d-11eb-9ebb-fd7e3a2a2331.png)

Maybe there are several processes running in same time on your device. And other processes may ocuppy some resources.

**Comment by shuo-ouyang** [comment]
Thanks, I got approximate stable results on a GTX 1080 device with CUDA 10.2.
