### ISSUE TITLE
Performance issue compared to MXNet

### ISSUE THREAD

**Issue by shuo-ouyang** [openppl-public/ppl.nn#17]
Hi, guys, I tested openppl with different batch size and compared its inference performance to MXNet. IMHO, if the batch size increase exponentially,  the inference latency will increase near exponentially too. But the results in table below donot follow this rule. Therefore, I doubt that my test command is wrong, or the latency given by openppl is about a single sample instead of a single query?

~~By the way, I found that when `--dim` is specified, `--in-shapes` option does not seem to work properly.~~

### Environment
MXNet: 1.6.0
OpenPPL: 7dd75a1
TensorRT: 8.0
Device: GTX 1080
CUDA: 10.2

The table below shows latency (ms) of ResNet50_v1b, FP32
OpenPPL command: `pplnn --warmuptimes 400 --runningtimes 100 --enable-profiling --dims bs_3_224_224 --in-shapes bs_3_224_224 --onnx-model model.onnx`
MXNet inference code: [link](https://paste.ubuntu.com/p/MJmrjcnB5X/)
| batch size | 1 | 2 | 4 | 8 | 16 | 32 |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| MXNet | 5.814193 | 7.570517 | 11.836981 | 20.500102 | 36.853303 | 69.709606 |
| OpenPPL | 1.730683 | 1.818604 | 2.219570 | 2.222927 | 2.294234 | 2.958766 |
| TensorRT | 2.66706 | 4.01048 | 6.84147 | 12.4254 | 23.0325 | 43.8126 |

**Comment by openppl-public** [comment]
> OpenPPL command: `pplnn --warmuptimes 400 --runningtimes 100 --enable-profiling --dims bs_3_224_224 --in-shapes bs_3_224_224 --onnx-model model.onnx`

Fixed. Please try again.

**Comment by shuo-ouyang** [comment]
> > OpenPPL command: `pplnn --warmuptimes 400 --runningtimes 100 --enable-profiling --dims bs_3_224_224 --in-shapes bs_3_224_224 --onnx-model model.onnx`
> 
> Fixed. Please try again.

Thanks very much for your quick response. But the latency of openppl shown in the above table is still confusing, compared to mxnet and tensorrt.

**Comment by ltj2013** [comment]
> > > OpenPPL command: `pplnn --warmuptimes 400 --runningtimes 100 --enable-profiling --dims bs_3_224_224 --in-shapes bs_3_224_224 --onnx-model model.onnx`
> > 
> > 
> > Fixed. Please try again.
> 
> Thanks very much for your quick response. But the latency of openppl shown in the above table is still confusing, compared to mxnet and tensorrt.

Hi, OpenPPL only supports  FP16 precision on Turing Devices. Please test the inference performance on turing devices, such as Tesla T4.

**Comment by shuo-ouyang** [comment]
@ltj2013 Thanks for your reply, I got reasonable results on RTX 2080ti with FP16 precision.
