### ISSUE TITLE
PRelu、Dropout、Upsample ParseNodeInfo for node unsupported

### ISSUE THREAD

**Issue by liuqiaoping7** [openppl-public/ppl.nn#18]
(base) [qiao@VM-238-190-centos ~/ppl.nn]$ ./pplnn-build/tools/pplnn --onnx-model test.onnx --mm-policy mem --min-profiling-time 10 --warmuptimes 5 --core-binding --disable-avx512 
[INFO][2021-07-08 20:21:45.381][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58
[INFO][2021-07-08 20:21:45.381][pplnn.cc:127] ***** register X86Engine *****
[ERROR][2021-07-08 20:21:45.384][graph_parser.cc:169] can not find param parser info of type[:PRelu]
[ERROR][2021-07-08 20:21:45.384][graph_parser.cc:195] ParseNodeInfo for node[] failed: unsupported
[ERROR][2021-07-08 20:21:45.384][graph_parser.cc:262] ParseGraphNode failed.
[ERROR][2021-07-08 20:21:45.384][model_parser.cc:76] parse graph failed: unsupported
[ERROR][2021-07-08 20:21:45.385][runtime_builder_impl.cc:50] parse graph failed: unsupported
[ERROR][2021-07-08 20:21:45.385][onnx_runtime_builder_factory.cc:59] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-08 20:21:45.385][pplnn.cc:714] create OnnxRuntimeBuilder failed.
(base) [qiao@VM-238-190-centos ~/ppl.nn]$ ./pplnn-build/tools/pplnn --onnx-model ~/test.onnx --mm-policy mem --min-profiling-time 10 --warmuptimes 5 --core-binding --disable-avx512 
[INFO][2021-07-08 20:49:47.035][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58
[INFO][2021-07-08 20:49:47.035][pplnn.cc:127] ***** register X86Engine *****
[ERROR][2021-07-08 20:49:47.039][graph_parser.cc:169] can not find param parser info of type[:Neg]
[ERROR][2021-07-08 20:49:47.039][graph_parser.cc:195] ParseNodeInfo for node[] failed: unsupported
[ERROR][2021-07-08 20:49:47.039][graph_parser.cc:262] ParseGraphNode failed.
[ERROR][2021-07-08 20:49:47.039][model_parser.cc:76] parse graph failed: unsupported
[ERROR][2021-07-08 20:49:47.039][runtime_builder_impl.cc:50] parse graph failed: unsupported
[ERROR][2021-07-08 20:49:47.039][onnx_runtime_builder_factory.cc:59] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-08 20:49:47.040][pplnn.cc:714] create OnnxRuntimeBuilder failed.
(base) [qiao@VM-238-190-centos ~/ppl.nn]$ ./pplnn-build/tools/pplnn --onnx-model ~/test.onnx --mm-policy mem --min-profiling-time 10 --warmuptimes 5 --core-binding --disable-avx512 
[INFO][2021-07-08 20:55:12.258][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58
[INFO][2021-07-08 20:55:12.258][pplnn.cc:127] ***** register X86Engine *****
[ERROR][2021-07-08 20:55:12.266][graph_parser.cc:169] can not find param parser info of type[:Dropout]
[ERROR][2021-07-08 20:55:12.266][graph_parser.cc:195] ParseNodeInfo for node[] failed: unsupported
[ERROR][2021-07-08 20:55:12.266][graph_parser.cc:262] ParseGraphNode failed.
[ERROR][2021-07-08 20:55:12.266][model_parser.cc:76] parse graph failed: unsupported
[ERROR][2021-07-08 20:55:12.267][runtime_builder_impl.cc:50] parse graph failed: unsupported
[ERROR][2021-07-08 20:55:12.267][onnx_runtime_builder_factory.cc:59] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-08 20:55:12.268][pplnn.cc:714] create OnnxRuntimeBuilder failed.
(base) [qiao@VM-238-190-centos ~/ppl.nn]$ ./pplnn-build/tools/pplnn --onnx-model ~/test.onnx --mm-policy mem --min-profiling-time 10 --warmuptimes 5 --core-binding --disable-avx512 
[INFO][2021-07-08 20:58:17.767][pplnn.cc:700] ppl.nn version: 513e6122dd90f619da0e550a8a3dc5e3184e5c58
[INFO][2021-07-08 20:58:17.767][pplnn.cc:127] ***** register X86Engine *****
[ERROR][2021-07-08 20:58:17.770][graph_parser.cc:169] can not find param parser info of type[:Upsample]
[ERROR][2021-07-08 20:58:17.770][graph_parser.cc:195] ParseNodeInfo for node[] failed: unsupported
[ERROR][2021-07-08 20:58:17.770][graph_parser.cc:262] ParseGraphNode failed.
[ERROR][2021-07-08 20:58:17.770][model_parser.cc:76] parse graph failed: unsupported
[ERROR][2021-07-08 20:58:17.770][runtime_builder_impl.cc:50] parse graph failed: unsupported
[ERROR][2021-07-08 20:58:17.771][onnx_runtime_builder_factory.cc:59] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-08 20:58:17.771][pplnn.cc:714] create OnnxRuntimeBuilder failed.

您好，请问PRelu、Dropout、Upsample这些网络层是onnx模型文件问题还是目前不支持呢？

**Comment by openppl-public** [comment]
> 您好，请问PRelu、Dropout、Upsample这些网络层是onnx模型文件问题还是目前不支持呢？

目前还不支持。参考这个文档：https://github.com/openppl-public/ppl.nn/blob/master/docs/en/supported-ops-and-platforms.md

**Comment by liuqiaoping7** [comment]
> > 您好，请问PRelu、Dropout、Upsample这些网络层是onnx模型文件问题还是目前不支持呢？
> 
> 目前还不支持。参考这个文档：https://github.com/openppl-public/ppl.nn/blob/master/docs/en/supported-ops-and-platforms.md

好的，感谢。
