### ISSUE TITLE
发现2个不支持的op

### ISSUE THREAD

**Issue by daoxian** [openppl-public/ppl.nn#206]
主干代码，centos7 编译后，运行命令：
pplnn --use-x86 --onnx-model  xxx.onnx

···
[INFO][2021-11-26 15:01:38.832][pplnn.cc:797] ppl.nn version: 63efb93accf552bca533a69461db8b2abd078c96-dirty
[INFO][2021-11-26 15:01:38.832][pplnn.cc:278] ***** register X86Engine *****
[ERROR][2021-11-26 15:01:39.001][graph_parser.cc:175] unsupported op: domain[], type[MaxPool], version[9]
[ERROR][2021-11-26 15:01:39.001][graph_parser.cc:202] ParseNodeInfo for node[MaxPool_2] failed: unsupported
[ERROR][2021-11-26 15:01:39.001][graph_parser.cc:267] ParseGraphNode failed.
[ERROR][2021-11-26 15:01:39.002][model_parser.cc:80] parse graph failed: unsupported
[ERROR][2021-11-26 15:01:39.002][runtime_builder_impl.cc:47] parse graph failed: unsupported
[ERROR][2021-11-26 15:01:39.002][onnx_runtime_builder_factory.cc:58] init RuntimeBuilder failed: unsupported
[ERROR][2021-11-26 15:01:39.016][pplnn.cc:817] create RuntimeBuilder failed.
···

···
[INFO][2021-11-26 15:01:51.409][pplnn.cc:797] ppl.nn version: 63efb93accf552bca533a69461db8b2abd078c96-dirty
[INFO][2021-11-26 15:01:51.409][pplnn.cc:278] ***** register X86Engine *****
[ERROR][2021-11-26 15:01:51.598][graph_parser.cc:175] unsupported op: domain[], type[CumSum], version[11]
[ERROR][2021-11-26 15:01:51.598][graph_parser.cc:202] ParseNodeInfo for node[CumSum_181] failed: unsupported
[ERROR][2021-11-26 15:01:51.598][graph_parser.cc:267] ParseGraphNode failed.
[ERROR][2021-11-26 15:01:51.598][model_parser.cc:80] parse graph failed: unsupported
[ERROR][2021-11-26 15:01:51.599][runtime_builder_impl.cc:47] parse graph failed: unsupported
[ERROR][2021-11-26 15:01:51.599][onnx_runtime_builder_factory.cc:58] init RuntimeBuilder failed: unsupported
[ERROR][2021-11-26 15:01:51.614][pplnn.cc:817] create RuntimeBuilder failed.
···

**Comment by Alcanderian** [comment]
第一个错误，`unsupported op: domain[], type[MaxPool], version[9]`，OpenPPL X86现在还没有提供opset=9的MaxPool支持，
第二个错误，`unsupported op: domain[], type[CumSum], version[11]`，现在也还没提供CumSum支持
这两个算子的以后会在不同的计划中分别支持上，感谢反馈
