### ISSUE TITLE
No module named 'pyppl'

### ISSUE THREAD

**Issue by pranerd** [openppl-public/ppl.nn#238]
Ubuntu 16.04.6
cmake: 3.16.6
Anaconda virtual enviroment: pytorch 1.7+cu101 

first git clone https://github.com/openppl-public/ppl.nn.git

Then ./build.sh -DHPCC_USE_X86_64=ON -DPPLNN_ENABLE_PYTHON_API=ON
 
Finally run the command PYTHONPATH=./pplnn-build/install python ./samples/python/maskrcnn_onnx/run_maskrcnn_onnx.py

it raise the error: 
![image](https://user-images.githubusercontent.com/19358928/147405451-00b3650b-be3c-4b13-ae37-e6e1e9552c42.png)
how to find the module named 'pyppl'

**Comment by ouonline** [comment]
> Ubuntu 16.04.6 cmake: 3.16.6 Anaconda virtual enviroment: pytorch 1.7+cu101
> 
> first git clone https://github.com/openppl-public/ppl.nn.git
> 
> Then ./build.sh -DHPCC_USE_X86_64=ON -DPPLNN_ENABLE_PYTHON_API=ON
> 
> Finally run the command PYTHONPATH=./pplnn-build/install python ./samples/python/maskrcnn_onnx/run_maskrcnn_onnx.py
> 
> it raise the error: ![image](https://user-images.githubusercontent.com/19358928/147405451-00b3650b-be3c-4b13-ae37-e6e1e9552c42.png) how to find the module named 'pyppl'

please change `PYTHONPATH=./pplnn-build/install` to `PYTHONPATH=./pplnn-build/install/lib`.

**Comment by pranerd** [comment]
thank you! it is solved.
