### ISSUE TITLE
windows cuda run error

### ISSUE THREAD

**Issue by VincentJing** [openppl-public/ppl.nn#271]
when I run benchmark example (pplnn), cuda compile code failed
![_4IZUYSC7PT A2R~{((Q0IA](https://user-images.githubusercontent.com/20381269/148381752-c53d655d-3f00-44a0-98b5-a5ceadd2068b.png)

**Comment by litianjian** [comment]
Hi, the issue has been fixed. Try again using the latest version, please.

**Comment by VincentJing** [comment]
thanks，I pull the latest code, which cuda version to use, when use cuda 11.5, the ptx version not supported.
![image](https://user-images.githubusercontent.com/20381269/148741745-5cf9f609-ce14-40e0-a422-19d438d91064.png)
