### ISSUE TITLE
centernet runs with memory error.

### ISSUE THREAD

**Issue by Maosquerade** [openppl-public/ppl.nn#315]
My gpu is Tesla T4, and sample model runs normally.
When I use centernet with --mm-policy=mem, it turns out erorr like this, but it can get an output.
![image](https://user-images.githubusercontent.com/41420892/150770734-c1c45b10-0702-4173-817e-fc71740035e4.png)
WHen I use --mm-policy=perf,  it gets error out of memory like this:
![image](https://user-images.githubusercontent.com/41420892/150770991-5592765a-76df-4089-a160-1d8f5fb9e3fa.png)
It seems they both end with memory error, is this error familiar to your team, or how can I avoid this error?

**Comment by Si-XU** [comment]
Could you give me your executive order? It seems that your input-shape has negitive value.

**Comment by Maosquerade** [comment]
> Could you share your executive order? It seems that your input-shape has negative value.

`./pplnn-build/tools/pplnn --onnx-model=/root/centernet.11.onnx --use-cuda=on --mm-policy=perf --in-shapes=1_3_640_640 --enable-profiling --warmup-iterations=10`
My executive order is this, I've set the input-shape, is this any problem?

**Comment by Si-XU** [comment]
Your order seems right. I tested several onnx model by your order like retinanet and maskrcnn. They are finished normally.
I guess the error is because your model. For example, your model have serveral inputs but you only give one shape.

Could you send your model to our offical email openppl.ai@hotmail.com. We will debug it ASAP.

**Comment by Maosquerade** [comment]
Thanks for reply！I've send the model to your email！

**Comment by Maosquerade** [comment]
Thanks for your reply! I've send the model to your email！

**Comment by Si-XU** [comment]
Your model is a pure static graph that batch size equals to -1. OpenPPL cannot change a static shape by  '--in-shapes'.
Actually, if you want a dynamic batch size, you should set it to a variable as follow:
![2](https://user-images.githubusercontent.com/61867914/153369987-3982bb45-4660-4014-86d3-f4df8f9237b8.png)

**Comment by Maosquerade** [comment]
Thanks for your advice! I modify the input dim and now it can run with --mm-policy=mem, but when I try --mm-policy=perf, it can compile normally but get cuda illegal memory accees error while running.
I use Tesla T4 and the memory should be enough, What's the difference between these two modes that makes this happen?








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openppl-public/ppl.nn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openppl-public/ppl.nn] centernet runs with memory error. (Issue #315)





 
Your model is a pure static graph that batch size equals to -1. OpenPPL cannot change a static shape by  '--in-shapes'.
 Actually, if you want a dynamic batch size, you should set it to a variable as follow:
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

centernet.new.11.onnx (49.61M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=78626565280184cd8f5ccb441f33501e025450070b0a01091f5506060a1e56540651485c0855071c035301515a0503500652065c39266252570c11004b5d07451c0c00121702531f5d0c0b1d3941&t=exs_ftn_download&code=2bee93b1

**Comment by Si-XU** [comment]
Memory is enough. The problem is conv + concat fusion.
As concat is the final op, we execute concat fusion and rewrite the output tensor pointer.
I will fix this bug today. Thanks for your testing.
