### ISSUE TITLE
windows编译出错

### ISSUE THREAD

**Issue by zgq91** [openppl-public/ppl.nn#328]
您好：
     在windows10 vs2017下 编译出错 出现未定义错误
E0020	未定义标识符 "_mm512_floor_ps"	pplkernelx86_static	ppl.nn\src\ppl\nn\engines\x86\impls\src\ppl\kernel\x86\common\math_avx512.h	103

**Comment by Alcanderian** [comment]
很抱歉我们暂时没有VS2017的编译测试环境。
可以尝试将`ppl.nn\src\ppl\nn\engines\x86\impls\src\ppl\kernel\x86\common\math_avx512.h 103`
改为`tmp = _mm512_roundscale_ps(fx, _MM_FROUND_FLOOR);`
如果可以通过编译，欢迎提交PR。
