### ISSUE TITLE
ubuntu 18.04 compiler error and fixed

### ISSUE THREAD

**Issue by yxpandjay** [openppl-public/ppl.nn#33]
when I compile the lastest code in 
ubuntu 18.04 
cmake 3.19.3

using  ./build.sh -DHPCC_USE_OPENMP=ON

it shows error like this:
![image](https://user-images.githubusercontent.com/31854414/126032632-c20e638d-d7ce-41b0-95d8-bb0e7d12bd82.png)

and when I add the header **#include< cmath>** in file src/ppl/nn/engines/x86/impls/test/utils/check.h , it works fine.

**Comment by yxpandjay** [comment]
#include<cmath>

**Comment by openppl-public** [comment]
Fixed.
