### ISSUE TITLE
core dump while use pplnn for x86 benchmarking

### ISSUE THREAD

**Issue by liyancas** [openppl-public/ppl.nn#332]
### System Info
OS: Ubuntu 16.04
Compiler: GCC-8.2
CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
The ONNX model uses opset11 which can run using TensorRT and ONNXRuntime

### Error Message as follows:
----------------------------

(perf) λ 96fbdb7483e1 /work/github/ppl.nn/pplnn-build/tools {master} bash test.sh
[INFO][2022-01-29 02:22:15.166][pplnn.cc:1053] ppl.nn version: cf852893f60b0a804e862aad0df1d62a3c8aa673
[INFO][2022-01-29 02:22:15.210][pplnn.cc:332] ***** register X86Engine *****
[INFO][2022-01-29 02:22:15.294][engine_graph_partitioner.cc:103] total partition(s) of graph[paddle-onnx]: 1.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
test.sh: line 8: 56259 Aborted                 (core dumped) ./pplnn --use-x86 --onnx-model ./models/MobileNetV1.onnx --mm-policy mem --enable-profiling --min-profiling-seconds 10 --warmup-iterations

**Comment by ouonline** [comment]
please send your model to openppl.ai@hotmail.com
