### ISSUE TITLE
Compile failed: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by nash-min-debug** [openppl-public/ppl.nn#349]
First, thanks for your work.

When I compiled `openppl` on docker, it returns an error: 
```
/root/ppl.nn/deps/pybind11/include/pybind11/detail/common.h:186:10: fatal error: Python.h: No such file or directory
```

My base image environment:
```
os: Ubuntu20.04
python: 3.8.10
```

I tried to install `libpython3.8-dev`, then locate `Python.h` in `/usr/include/python3.8/`. After that, I tried to recompile and still report an error `Python.h: No such file or directory`
However, I have successfully compiled `openppl` on my host, host environment:
```
os: Ubuntu16.04
chip: x64
Pybind has been preinstalled 
```

Next, I tried to `pip install pybind` and delete `hpcc declare pybind` function in `deps.cmake`, it still same error. And maybe some packages' versions are too old.

So, could you release a docker image or help me solve this problem?
Thanks!

**Comment by ouonline** [comment]
refer to the docker config: https://github.com/openppl-public/ppl.nn/tree/master/docker or the building instruction https://github.com/openppl-public/ppl.nn/blob/master/docs/en/building-from-source.md for more details.

**Comment by nash-min-debug** [comment]
add `ENV CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/python3.8/` in doker file.
My dockerfile:
```
FROM homebrew/ubuntu20.04:latest

USER root
WORKDIR /root

SHELL [ "/bin/bash", "-c" ]

RUN apt-get -y update && \
    apt-get install -y cmake && \
    apt-get install -y python3-pip && \
    apt-get install -y python3-dev && \
    apt-get install -y expect && \
    apt-get install -y build-essential

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

ENV CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/python3.8/

## compile ppl
COPY ppl.nn/ ppl.nn/
RUN cd ppl.nn && \
    chmod 777 ./build.sh && \
    ./build.sh -DHPCC_USE_X86_64=ON -DHPCC_USE_OPENMP=ON -DPPLNN_ENABLE_PYTHON_API=ON -DPYTHON3_INCLUDE_DIRS=/usr/lib/python3.8/site-packages && \
    cd .. && \
    rm -r ppl.nn/

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD [ "/bin/bash" ]
```

**Comment by ouonline** [comment]
> ./build.sh -DHPCC_USE_X86_64=ON -DHPCC_USE_OPENMP=ON -DPPLNN_ENABLE_PYTHON_API=ON -DPYTHON3_INCLUDE_DIRS=/usr/lib/python3.8/site-packages && \

change the `PYTHON3_INCLUDE_DIRS` to `/usr/include/python3.8/` instead of using `CPLUS_INCLUDE_PATH`.

**Comment by nash-min-debug** [comment]
> 

Thanks!
