### ISSUE TITLE
x86引擎运行没问题，但cuda引擎无法运行，会卡在Compiling Conv_0直至64G内存全部耗尽

### ISSUE THREAD

**Issue by stujiajia** [openppl-public/ppl.nn#361]
[DEBUG][2022-02-26 11:23:12.125][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_127_Fused]
[DEBUG][2022-02-26 11:23:12.126][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_139_Fused]
[DEBUG][2022-02-26 11:23:12.126][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_151_Fused]
[DEBUG][2022-02-26 11:23:12.126][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_163_Fused]
[DEBUG][2022-02-26 11:23:12.126][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_176_Fused]
[DEBUG][2022-02-26 11:23:12.126][fuse_shape_optimizer.cc:257] Output count 1 for fused shape node[Shape_185_Fused]
[INFO][2022-02-26 11:23:12.127][engine_graph_partitioner.cc:103] total partition(s) of graph[torch-jit-export]: 1.
[DEBUG][2022-02-26 11:23:12.153][opt_graph.cc:186] Can not reshape safely for node[Resize_170]
[DEBUG][2022-02-26 11:23:12.154][opt_graph.cc:186] Can not reshape safely for node[Resize_158]
[DEBUG][2022-02-26 11:23:12.155][opt_graph.cc:186] Can not reshape safely for node[Resize_146]
[DEBUG][2022-02-26 11:23:12.156][opt_graph.cc:186] Can not reshape safely for node[Resize_134]
[DEBUG][2022-02-26 11:23:12.156][reshape_concat.cc:43] ERROR: input[1]'s dim[2]'s value[1] != input[0]'s dim[2]'s value[37].
[DEBUG][2022-02-26 11:23:12.156][opt_graph.cc:186] Can not reshape safely for node[Concat_171]
[DEBUG][2022-02-26 11:23:12.172][opt_graph.cc:186] Can not reshape safely for node[Resize_183]
[DEBUG][2022-02-26 11:23:12.172][opt_graph.cc:186] Can not reshape safely for node[Resize_192]
[DEBUG][2022-02-26 11:23:12.173][opt_graph.cc:200] Create 305 TensorImpl
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_172] and nextnode[Relu_173]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_124] and nextnode[Relu_125]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_136] and nextnode[Relu_137]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_148] and nextnode[Relu_149]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_160] and nextnode[Relu_161]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_120] and nextnode[Add_121]
[DEBUG][2022-02-26 11:23:12.173][fs_conv.cc:80] Fuse node[Conv_120] and nextnode[Relu_122]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_118] and nextnode[Relu_119]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_116] and nextnode[Relu_117]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_113] and nextnode[Add_114]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_113] and nextnode[Relu_115]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_111] and nextnode[Relu_112]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_109] and nextnode[Relu_110]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_105] and nextnode[Add_107]
[DEBUG][2022-02-26 11:23:12.174][fs_conv.cc:80] Fuse node[Conv_105] and nextnode[Relu_108]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_103] and nextnode[Relu_104]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_101] and nextnode[Relu_102]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_98] and nextnode[Add_99]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_98] and nextnode[Relu_100]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_96] and nextnode[Relu_97]
[DEBUG][2022-02-26 11:23:12.175][fs_conv.cc:80] Fuse node[Conv_94] and nextnode[Relu_95]
[DEBUG][2022-02-26 11:23:12.176][fs_conv.cc:80] Fuse node[Conv_91] and nextnode[Add_92]
[DEBUG][2022-02-26 11:23:12.176][fs_conv.cc:80] Fuse node[Conv_91] and nextnode[Relu_93]
[DEBUG][2022-02-26 11:23:12.176][fs_conv.cc:80] Fuse node[Conv_89] and nextnode[Relu_90]
[DEBUG][2022-02-26 11:23:12.176][fs_conv.cc:80] Fuse node[Conv_87] and nextnode[Relu_88]
[DEBUG][2022-02-26 11:23:12.176][fs_conv.cc:80] Fuse node[Conv_84] and nextnode[Add_85]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_84] and nextnode[Relu_86]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_82] and nextnode[Relu_83]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_80] and nextnode[Relu_81]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_77] and nextnode[Add_78]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_77] and nextnode[Relu_79]
[DEBUG][2022-02-26 11:23:12.177][fs_conv.cc:80] Fuse node[Conv_75] and nextnode[Relu_76]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_73] and nextnode[Relu_74]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_70] and nextnode[Add_71]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_70] and nextnode[Relu_72]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_68] and nextnode[Relu_69]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_66] and nextnode[Relu_67]
[DEBUG][2022-02-26 11:23:12.178][fs_conv.cc:80] Fuse node[Conv_62] and nextnode[Add_64]
[DEBUG][2022-02-26 11:23:12.179][fs_conv.cc:80] Fuse node[Conv_62] and nextnode[Relu_65]
[DEBUG][2022-02-26 11:23:12.180][fs_conv.cc:80] Fuse node[Conv_60] and nextnode[Relu_61]
[DEBUG][2022-02-26 11:23:12.180][fs_conv.cc:80] Fuse node[Conv_58] and nextnode[Relu_59]
[DEBUG][2022-02-26 11:23:12.181][fs_conv.cc:80] Fuse node[Conv_55] and nextnode[Add_56]
[DEBUG][2022-02-26 11:23:12.182][fs_conv.cc:80] Fuse node[Conv_55] and nextnode[Relu_57]
[DEBUG][2022-02-26 11:23:12.182][fs_conv.cc:80] Fuse node[Conv_53] and nextnode[Relu_54]
[DEBUG][2022-02-26 11:23:12.182][fs_conv.cc:80] Fuse node[Conv_51] and nextnode[Relu_52]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_48] and nextnode[Add_49]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_48] and nextnode[Relu_50]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_46] and nextnode[Relu_47]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_44] and nextnode[Relu_45]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_41] and nextnode[Add_42]
[DEBUG][2022-02-26 11:23:12.183][fs_conv.cc:80] Fuse node[Conv_41] and nextnode[Relu_43]
[DEBUG][2022-02-26 11:23:12.184][fs_conv.cc:80] Fuse node[Conv_39] and nextnode[Relu_40]
[DEBUG][2022-02-26 11:23:12.184][fs_conv.cc:80] Fuse node[Conv_37] and nextnode[Relu_38]
[DEBUG][2022-02-26 11:23:12.184][fs_conv.cc:80] Fuse node[Conv_33] and nextnode[Add_35]
[DEBUG][2022-02-26 11:23:12.184][fs_conv.cc:80] Fuse node[Conv_33] and nextnode[Relu_36]
[DEBUG][2022-02-26 11:23:12.185][fs_conv.cc:80] Fuse node[Conv_31] and nextnode[Relu_32]
[DEBUG][2022-02-26 11:23:12.185][fs_conv.cc:80] Fuse node[Conv_29] and nextnode[Relu_30]
[DEBUG][2022-02-26 11:23:12.185][fs_conv.cc:80] Fuse node[Conv_26] and nextnode[Add_27]
[DEBUG][2022-02-26 11:23:12.185][fs_conv.cc:80] Fuse node[Conv_26] and nextnode[Relu_28]
[DEBUG][2022-02-26 11:23:12.185][fs_conv.cc:80] Fuse node[Conv_24] and nextnode[Relu_25]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_22] and nextnode[Relu_23]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_19] and nextnode[Add_20]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_19] and nextnode[Relu_21]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_17] and nextnode[Relu_18]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_15] and nextnode[Relu_16]
[DEBUG][2022-02-26 11:23:12.186][fs_conv.cc:80] Fuse node[Conv_11] and nextnode[Add_13]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_11] and nextnode[Relu_14]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_9] and nextnode[Relu_10]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_7] and nextnode[Relu_8]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_4] and nextnode[Relu_5]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_2] and nextnode[Relu_3]
[DEBUG][2022-02-26 11:23:12.187][fs_conv.cc:80] Fuse node[Conv_0] and nextnode[Relu_1]
[INFO][2022-02-26 11:23:12.192][opt_graph.cc:311] added 261 new bridge kernels
[INFO][2022-02-26 11:23:12.724][algo_conv_hmma.cc:126] Compiling Conv_0

**Comment by ouonline** [comment]
* What are the problems?(snapshots or detailed error messages)

* What's the operating system ppl.nn runs on?

* What's the compiler and its version?

* What are the commands used to build ppl.nn?

* What are the execution commands?

* models and inputs for reproducing these problems (sends them to openppl.ai@hotmail.com if necessary)

**Comment by stujiajia** [comment]
> * 问题出在哪里？（快照或详细的错误消息）
这是我的源码，是官方的示例，官方工程为pplnn_samples_api_intro，在执行main函数的时候，下面这段代码会卡住，不管什么模型都无法执行下去，也没有报错，直到电脑64G内存耗尽。但是在X86引擎下，可以出结果，cuda引擎下会卡住直至内存耗尽。
   auto status = builder->Init(model_file, engine_ptrs.data(), engine_ptrs.size());
    if (status != RC_SUCCESS) {
        cerr << "init OnnxRuntimeBuilder failed: " << GetRetCodeStr(status) << endl;
        return -1;
    }
全部代码如下：
int main(void) {
    const char* model_file = "D:/develop_softwares/ppl.nn-master/tests/testdata/conv.onnx";
    auto builder = unique_ptr<OnnxRuntimeBuilder>(OnnxRuntimeBuilderFactory::Create());
    if (!builder) {
        cerr << "create RuntimeBuilder failed." << endl;
        return -1;
    }
    auto cuda_engine = CudaEngineFactory::Create(CudaEngineOptions());
    vector<unique_ptr<Engine>> engines;
    engines.emplace_back(unique_ptr<Engine>(cuda_engine));
    vector<Engine*> engine_ptrs(engines.size());
    for (uint32_t i = 0; i < engines.size(); ++i) {
        engine_ptrs[i] = engines[i].get();
    }
    auto status = builder->Init(model_file, engine_ptrs.data(), engine_ptrs.size());
    if (status != RC_SUCCESS) {
        cerr << "init OnnxRuntimeBuilder failed: " << GetRetCodeStr(status) << endl;
        return -1;
    }
    status = builder->Preprocess();
    if (status != RC_SUCCESS) {
        cerr << "builder preprocess failed: " << GetRetCodeStr(status) << endl;
        return status;
    }
    auto runtime = unique_ptr<Runtime>(builder->CreateRuntime());
    if (!runtime) {
        cerr << "CreateRuntime failed." << endl;
        return -1;
    }
    if (!SetRandomInputs(runtime.get())) {
        cerr << "SetRandomInputs failed." << endl;
        return -1;
    }
    status = runtime->Run();
    if (status != RC_SUCCESS) {
        cerr << "Run() failed: " << GetRetCodeStr(status) << endl;
        return -1;
    }
    PrintInputOutputInfo(runtime.get());
    return 0;
}
> * ppl.nn 在什么操作系统上运行？
windows 10 家庭版   

> * 编译器及其版本是什么？
vs 2019  TensorRT-8.2.3.0   CUDA11.3  cmake3.23.0  显卡2080super以及3090都有试过，问题相同。

> * 用于构建 ppl.nn 的命令是什么？执行命令是什么？
根据官方例子，修改的源码，官方工程为pplnn_samples_api_intro
debug下调试

> * 用于重现这些问题的模型和输入（如有必要，请将其发送到 [openppl.ai@hotmail.com](mailto:openppl.ai@hotmail.com)）
模型为官方提供的测试模型ppl.nn-master\tests\testdata\conv.onnx，我也试过yolo等其他模型,存在同样的问题。

除此之外，用官方源码pplnn_samples_api_intro，在X86引擎下推理，虽然有结果输出，单无法return 0，退出代码; 在执行代码最后一行return 0的时候，会出现内存异常,异常如下图。

![捕获](https://user-images.githubusercontent.com/54341865/155853713-42fc599f-8a57-4354-a89e-53a07ee11c82.PNG)
![捕获1](https://user-images.githubusercontent.com/54341865/155853753-f0104305-b5f3-4bc8-be07-0539434f179c.PNG)

**Comment by ouonline** [comment]
x86 api_intro.crash 的问题已经修复，将 builder 放到 engine 之后初始化就可以了。

cuda 的问题应该是 11.3 引起的，之前也有人报过类似的错误，如果方便的话可以用 cuda 其它版本试试（10.2，11.1 都是可以的），这个问题 cuda 的同事修复后会在这里回复。

**Comment by stujiajia** [comment]
how to solve this problem?

**Comment by Si-XU** [comment]
可以添加 --quick-select 参数暂时跳过 Compiling Conv_0，看看后面是否还有类似问题。

**Comment by stujiajia** [comment]
添加 --quick-select，测试了几种模型，可以跑通，但是yolo模型运行到一半会崩溃退出。模型我发送至您们团队邮箱了，期待你的回复。

**Comment by xinsuinizhuan** [comment]
> 添加 --quick-select，测试了几种模型，可以跑通，但是yolo模型运行到一半会崩溃退出。模型我发送至您们团队邮箱了，期待你的回复。

你是什么平台跑的？windows? vs2019能编译过吗？跑过yolov5吗？速度咋样？比onnxruntime

**Comment by xinsuinizhuan** [comment]
希望多出几个demo,，比如跑一下yolov5模型
