### ISSUE TITLE
Is there a way to install from pip or conda?

### ISSUE THREAD

**Issue by PkuDavidGuan** [openppl-public/ppl.nn#391]
Hi, developers, I notice that now ppl could be installed by source, Is there a way to install from pip or conda?

**Comment by ouonline** [comment]
will be available when v1.0.0 is released(may be on 2022.6). before that you can only build and install ppl from source.

**Comment by jinfagang** [comment]
@ouonline Does pip install avaiable now?

**Comment by ouonline** [comment]
> @ouonline Does pip install avaiable now?

not yet. v1.0.0 is not released yet.
