### ISSUE TITLE
windows VS2019可以编译吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [openppl-public/ppl.nn#401]

**Comment by xinsuinizhuan** [comment]
cmake编译的时候，报错：
Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.
The C compiler identification is MSVC 19.29.30141.0
The CXX compiler identification is MSVC 19.29.30141.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Populating hpcc
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.

-- Configuring done

-- Generating done

-- Build files have been written to: D:/vison_software/pplnn/ppl.nn/deps/hpcc-subbuild

用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。


  Checking Build System

  Creating directories for 'hpcc-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/hpcc-subbuild/CMakeLists.txt

  Performing download step (git clone) for 'hpcc-populate'

  Cloning into 'hpcc'...

  fatal: unable to access 'https://github.com/openppl-public/hpcc.git/': OpenSSL SSL_read: Connection was reset, errno 10054

  Cloning into 'hpcc'...

  -- Had to git clone more than once:

            2 times.

  HEAD is now at 1b714b9 add `-fno-strict-aliasing` for gcc

  Performing update step for 'hpcc-populate'

  No patch step for 'hpcc-populate'

  No configure step for 'hpcc-populate'

  No build step for 'hpcc-populate'

  No install step for 'hpcc-populate'

  No test step for 'hpcc-populate'

  Completed 'hpcc-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/hpcc-subbuild/CMakeLists.txt

The ASM compiler identification is MSVC
Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Performing Test HAVE_C_FLAG_MP
Performing Test HAVE_C_FLAG_MP - Success
Performing Test HAVE_C_FLAG_OPENMP
Performing Test HAVE_C_FLAG_OPENMP - Success
Performing Test HAVE_CXX_FLAG_MP
Performing Test HAVE_CXX_FLAG_MP - Success
Performing Test HAVE_CXX_FLAG_OPENMP
Performing Test HAVE_CXX_FLAG_OPENMP - Success
Performing Test HAVE_CXX_FLAG_WD4244
Performing Test HAVE_CXX_FLAG_WD4244 - Success
Performing Test HAVE_CXX_FLAG_WD4251
Performing Test HAVE_CXX_FLAG_WD4251 - Success
Performing Test HAVE_CXX_FLAG_WD4267
Performing Test HAVE_CXX_FLAG_WD4267 - Success
Performing Test HAVE_CXX_FLAG_WD4305
Performing Test HAVE_CXX_FLAG_WD4305 - Success
Performing Test HAVE_CXX_FLAG_WD4503
Performing Test HAVE_CXX_FLAG_WD4503 - Success
Performing Test HAVE_CXX_FLAG_WD4819
Performing Test HAVE_CXX_FLAG_WD4819 - Success
Performing Test HAVE_CXX_FLAG_WD4800
Performing Test HAVE_CXX_FLAG_WD4800 - Success
Performing Test HAVE_CXX_FLAG_WD4996
Performing Test HAVE_CXX_FLAG_WD4996 - Success
Performing Test HAVE_CXX_FLAG_WD4828
Performing Test HAVE_CXX_FLAG_WD4828 - Success
Performing Test HAVE_CXX_FLAG_UTF_8
Performing Test HAVE_CXX_FLAG_UTF_8 - Success
Populating rapidjson
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.

-- Configuring done

-- Generating done

-- Build files have been written to: D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild

用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。


  Checking Build System

  Creating directories for 'rapidjson-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild/CMakeLists.txt

  Performing download step (download, verify and extract) for 'rapidjson-populate'

  -- Downloading...

     dst='D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild/rapidjson-populate-prefix/src/2e8f5d897d9d461a7273b4b812b0127f321b1dcf.zip'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/Tencent/rapidjson/archive/2e8f5d897d9d461a7273b4b812b0127f321b1dcf.zip'

  -- [download 100% complete]

  -- verifying file...

         file='D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild/rapidjson-populate-prefix/src/2e8f5d897d9d461a7273b4b812b0127f321b1dcf.zip'

  -- Downloading... done

  -- extracting...

       src='D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild/rapidjson-populate-prefix/src/2e8f5d897d9d461a7273b4b812b0127f321b1dcf.zip'
       dst='D:/vison_software/pplnn/ppl.nn/deps/rapidjson'

  -- extracting... [tar xfz]

  -- extracting... [analysis]

  -- extracting... [rename]

  -- extracting... [clean up]

  -- extracting... done

  No update step for 'rapidjson-populate'

  No patch step for 'rapidjson-populate'

  No configure step for 'rapidjson-populate'

  No build step for 'rapidjson-populate'

  No install step for 'rapidjson-populate'

  No test step for 'rapidjson-populate'

  Completed 'rapidjson-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/rapidjson-subbuild/CMakeLists.txt

CMake Deprecation Warning at deps/rapidjson/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


Populating pplcommon
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.

-- Configuring done

-- Generating done

-- Build files have been written to: D:/vison_software/pplnn/ppl.nn/deps/pplcommon-subbuild

用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。


  Checking Build System

  Creating directories for 'pplcommon-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/pplcommon-subbuild/CMakeLists.txt

  Performing download step (git clone) for 'pplcommon-populate'

  Cloning into 'pplcommon'...

  HEAD is now at 94371a8 update hpcc and luacpp

  Performing update step for 'pplcommon-populate'

  No patch step for 'pplcommon-populate'

  No configure step for 'pplcommon-populate'

  No build step for 'pplcommon-populate'

  No install step for 'pplcommon-populate'

  No test step for 'pplcommon-populate'

  Completed 'pplcommon-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/pplcommon-subbuild/CMakeLists.txt

Populating protobuf
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.

-- Configuring done

-- Generating done

-- Build files have been written to: D:/vison_software/pplnn/ppl.nn/deps/protobuf-subbuild

用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。


  Checking Build System

  Creating directories for 'protobuf-populate'

  Building Custom Rule D:/vison_software/pplnn/ppl.nn/deps/protobuf-subbuild/CMakeLists.txt

  Performing download step (download, verify and extract) for 'protobuf-populate'

  -- Downloading...

     dst='D:/vison_software/pplnn/ppl.nn/deps/protobuf-subbuild/protobuf-populate-prefix/src/protobuf-cpp-3.12.4.zip'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/protocolbuffers/protobuf/releases/download/v3.12.4/protobuf-cpp-3.12.4.zip'

  CMake Error at protobuf-subbuild/protobuf-populate-prefix/src/protobuf-populate-stamp/download-protobuf-populate.cmake:170 (message):

    Each download failed!
  

CUSTOMBUILD : error : downloading 'https://github.com/protocolbuffers/protobuf/releases/download/v3.12.4/protobuf-cpp-3.12.4.zip' failed [D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\protobuf-populate.vcxproj]

            status_code: 28

            status_string: "Timeout was reached"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 20.205.243.166:443...
  

    connect to 20.205.243.166 port 443 failed: Timed out
  
    Failed to connect to github.com port 443: Timed out
  
    Closing connection 0
  
    

  

            --- LOG END ---
            
      
  
  

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-popula
te-mkdir.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-download.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-update.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-patch.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-configure.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-build.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-install.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\5e0dc590a1713fe7757b1dbcf6ad7755\protobuf-populate-test.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\cfd23ec04a4a27a26fc3326c6809b829\protobuf-popul
ate-complete.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeFiles\18bbda1cacedef5ff009dfccbcd3f3a2\protobuf-populate.rule;D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\CMakeLists.txt”的自定义生成已退出，代码为 1。 [D:\vison_software\pplnn\ppl.nn\deps\protobuf-subbuild\protobuf-populate.vcxproj]

CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FetchContent.cmake:1017 (message):
  Build step for protobuf failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FetchContent.cmake:1146:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FetchContent.cmake:1146 (cmake_language)
  cmake/protobuf.cmake:4 (FetchContent_Populate)
  CMakeLists.txt:130 (include)


Configuring incomplete, errors occurred!
See also "D:/vison_software/pplnn/ppl.nn/build/CMakeFiles/CMakeOutput.log".
See also "D:/vison_software/pplnn/ppl.nn/build/CMakeFiles/CMakeError.log".

**Comment by ouonline** [comment]
please answer the questions listed in the bug report template.

**Comment by xinsuinizhuan** [comment]
It is ok. close it. I  compile it ,in winows ,vs2019
