### ISSUE TITLE
About the core J1900 run the python demo occur get unsupported isa 0

### ISSUE THREAD

**Issue by F0xZz** [openppl-public/ppl.nn#410]
![Screenshot from 2022-03-24 10-39-10](https://user-images.githubusercontent.com/41953310/159831226-5f31fb8e-3a2e-4529-9d45-cce12b2b1242.png)

cpu core J1900
vendor_id	: GenuineIntel
cpu family	: 6
model		: 55
model name	: Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
stepping	: 9
microcode	: 0x90c
cpu MHz		: 2042.652
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 mds msbds_only
bogomips	: 4000.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual

gcc 7.5.0
os:Ubuntu18.04 LTS
PPLNN version: [0.6.3]

I use the command:
PYTHONPATH=./pplnn-build/install/lib python3 ./tools/pplnn.py --use-x86 --onnx-model tests/testdata/conv.onnx

i find maybe the core is too elder that not support this?

**Comment by Alcanderian** [comment]
It may be some problem with our cpuid detection
Can you run `pplcommon-build/cpuinfo` in the build dir and paste it to me?

**Comment by F0xZz** [comment]
> It may be some problem with our cpuid detection Can you build with the lastest master. And run `pplcommon-build/cpuinfo` in the build dir and paste it to me?

cpuinfo
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:27] Info From CPUID:
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:28] Vendor: GenuineIntel
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:29] VNNI  : 0
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:30] AVX512: 0
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:31] AVX2  : 0
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:32] FMA3  : 0
[INFO][2022-03-24 13:01:52.810][cpuinfo.cc:33] AVX   : 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:34] SSE   : 1
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:35] L1 D-Cahce: 24576
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:36] L2 Cahce: 1048576
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:37] L3 Cahce: 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:39] Info From RUN:
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:40] Vendor: GenuineIntel
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:41] VNNI  : 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:42] AVX512: 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:43] AVX2  : 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:44] FMA3  : 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:45] AVX   : 1
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:46] SSE   : 0
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:47] L1 D-Cahce: 24576
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:48] L2 Cahce: 1048576
[INFO][2022-03-24 13:01:52.811][cpuinfo.cc:49] L3 Cahce: 0

**Comment by Alcanderian** [comment]
> > It may be some problem with our cpuid detection Can you build with the lastest master. And run `pplcommon-build/cpuinfo` in the build dir and paste it to me?
> 
> cpuinfo [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:27] Info From CPUID: [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:28] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:29] VNNI : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:30] AVX512: 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:31] AVX2 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:32] FMA3 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:33] AVX : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:34] SSE : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:35] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:36] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:37] L3 Cahce: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:39] Info From RUN: [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:40] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:41] VNNI : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:42] AVX512: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:43] AVX2 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:44] FMA3 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:45] AVX : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:46] SSE : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:47] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:48] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:49] L3 Cahce: 0

It seems that the cpuinfo by run does not work well.
I  has changed the ISA detection method to `detect by CPUID` in the lastest master(commit d1d8b2ab5ddd1e4be662770476617f9ff7538842).

Please delete `deps` folder under ppl.nn. And then pull and rebuild openppl.

Hope it works.

**Comment by F0xZz** [comment]
> > > It may be some problem with our cpuid detection Can you build with the lastest master. And run `pplcommon-build/cpuinfo` in the build dir and paste it to me?
> > 
> > 
> > cpuinfo [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:27] Info From CPUID: [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:28] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:29] VNNI : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:30] AVX512: 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:31] AVX2 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:32] FMA3 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:33] AVX : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:34] SSE : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:35] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:36] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:37] L3 Cahce: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:39] Info From RUN: [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:40] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:41] VNNI : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:42] AVX512: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:43] AVX2 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:44] FMA3 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:45] AVX : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:46] SSE : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:47] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:48] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:49] L3 Cahce: 0
> 
> It seems that the cpuinfo by run does not work well. I has changed the ISA detection method to `detect by CPUID` in the lastest master(commit [d1d8b2a](https://github.com/openppl-public/ppl.nn/commit/d1d8b2ab5ddd1e4be662770476617f9ff7538842)).
> 
> Please delete `deps` folder under ppl.nn. And then pull and rebuild openppl.
> 
> Hope it works.

i run the Tengine framework has occur the illeage instruction (core dump) and i set the AVX2 instruction set to OFF then  i can  run the benchmark. but i set the ppl.nn framework to the set 
https://github.com/openppl-public/ppl.nn/blob/d1d8b2ab5ddd1e4be662770476617f9ff7538842/src/ppl/nn/engines/x86/impls/CMakeLists.txt#L5
option(PPL_USE_X86_AVX512 "Build x86 kernel with openmp support." ON) 
set this to OFF and remake

but also occur the same problem

as u say method i will test in few days

**Comment by F0xZz** [comment]
I test the code  and git clone in the 20220324
so the ppl.nn/deps is already lastest
i test the git checkout -b d1d8b2ab5ddd1e4be662770476617f9ff7538842
and i remake the code also show this info maybe i am some wrong with my test

[INFO][2022-03-25 12:44:51.494][cpuinfo.cc:27] Info From CPUID:
[INFO][2022-03-25 12:44:51.494][cpuinfo.cc:28] Vendor: GenuineIntel
[INFO][2022-03-25 12:44:51.494][cpuinfo.cc:29] VNNI  : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:30] AVX512: 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:31] AVX2  : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:32] FMA3  : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:33] AVX   : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:34] SSE   : 1
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:35] L1 D-Cahce: 24576
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:36] L2 Cahce: 1048576
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:37] L3 Cahce: 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:39] Info From RUN:
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:40] Vendor: GenuineIntel
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:41] VNNI  : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:42] AVX512: 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:43] AVX2  : 1
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:44] FMA3  : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:45] AVX   : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:46] SSE   : 0
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:47] L1 D-Cahce: 24576
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:48] L2 Cahce: 1048576
[INFO][2022-03-25 12:44:51.495][cpuinfo.cc:49] L3 Cahce: 0

**Comment by Alcanderian** [comment]
> > > > It may be some problem with our cpuid detection Can you build with the lastest master. And run `pplcommon-build/cpuinfo` in the build dir and paste it to me?
> > > 
> > > 
> > > cpuinfo [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:27] Info From CPUID: [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:28] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:29] VNNI : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:30] AVX512: 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:31] AVX2 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:32] FMA3 : 0 [INFO][2022-03-24 13:01:52.810][cpuinfo.cc:33] AVX : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:34] SSE : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:35] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:36] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:37] L3 Cahce: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:39] Info From RUN: [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:40] Vendor: GenuineIntel [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:41] VNNI : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:42] AVX512: 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:43] AVX2 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:44] FMA3 : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:45] AVX : 1 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:46] SSE : 0 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:47] L1 D-Cahce: 24576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:48] L2 Cahce: 1048576 [INFO][2022-03-24 13:01:52.811][cpuinfo.cc:49] L3 Cahce: 0
> > 
> > 
> > It seems that the cpuinfo by run does not work well. I has changed the ISA detection method to `detect by CPUID` in the lastest master(commit [d1d8b2a](https://github.com/openppl-public/ppl.nn/commit/d1d8b2ab5ddd1e4be662770476617f9ff7538842)).
> > Please delete `deps` folder under ppl.nn. And then pull and rebuild openppl.
> > Hope it works.
> 
> i run the Tengine framework has occur the illeage instruction (core dump) and i set the AVX2 instruction set to OFF then i can run the benchmark. but i set the ppl.nn framework to the set
> 
> https://github.com/openppl-public/ppl.nn/blob/d1d8b2ab5ddd1e4be662770476617f9ff7538842/src/ppl/nn/engines/x86/impls/CMakeLists.txt#L5
> 
> 
> option(PPL_USE_X86_AVX512 "Build x86 kernel with openmp support." ON)
> set this to OFF and remake
> but also occur the same problem
> 
> as u say method i will test in few days

OpenPPL use auto ISA detection so we will not use AVX512 util it has been detected.
So turn it OFF can only reduce the library binary size

**Comment by Alcanderian** [comment]
> I test the code and git clone in the 20220324 so the ppl.nn/deps is already lastest i test the git checkout -b [d1d8b2a](https://github.com/openppl-public/ppl.nn/commit/d1d8b2ab5ddd1e4be662770476617f9ff7538842) and i remake the code also show this info maybe i am some wrong with my test
> 
> [INFO][2022-03-25 12:44:51.494][cpuinfo.cc:27] Info From CPUID: [INFO][2022-03-25 12:44:51.494][cpuinfo.cc:28] Vendor: GenuineIntel [INFO][2022-03-25 12:44:51.494][cpuinfo.cc:29] VNNI : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:30] AVX512: 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:31] AVX2 : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:32] FMA3 : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:33] AVX : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:34] SSE : 1 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:35] L1 D-Cahce: 24576 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:36] L2 Cahce: 1048576 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:37] L3 Cahce: 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:39] Info From RUN: [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:40] Vendor: GenuineIntel [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:41] VNNI : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:42] AVX512: 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:43] AVX2 : 1 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:44] FMA3 : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:45] AVX : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:46] SSE : 0 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:47] L1 D-Cahce: 24576 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:48] L2 Cahce: 1048576 [INFO][2022-03-25 12:44:51.495][cpuinfo.cc:49] L3 Cahce: 0

Don't care about the result of `Info From RUN:`.
In the lastest ppl.common we deprecate `GetCPUInfoByRun` and use `GetCPUInfoByCPUID` instead
https://github.com/openppl-public/ppl.common/commit/a0cde88ad23fe18f690343219e57f914008dee9c

According to the result we can find that the `Info From CPUID:` is correct, so the benchmark may work with the lastest code
