### ISSUE TITLE
error about ppl.nn/tools/convert_onnx_opset_version.py

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppl.nn#473]
我尝试在我的代码中加入了 ppl.nn/tools/convert_onnx_opset_version.py，可是如果强行opset11转为opset11 （就是走一遍该代码流程），没有成功转换opset（报错）；或者就是存粹的想initializer转成constant，再constant转initializer，之后过其我的代码会出问题（本来不会出问题的）

叨扰问下后续会继续改进这个工具吗，确实onnx不同 opset所带来的问题还是很困扰人

**Comment by ZichenTian** [comment]
> 我尝试在我的代码中加入了 ppl.nn/tools/convert_onnx_opset_version.py，可是如果强行opset11转为opset11 （就是走一遍该代码流程），没有成功转换opset（报错）；或者就是存粹的想initializer转成constant，再constant转initializer，之后过其我的代码会出问题（本来不会出问题的）
> 
> 叨扰问下后续会继续改进这个工具吗，确实onnx不同 opset所带来的问题还是很困扰人

这个工具当时的目的是为了应对 onnx < 1.11 版本里 version converter 的问题加的临时解决方案

当时版本的 onnx version converter 在模型里面有 initializer 的时候，会转换失败，所以加了这么个工具，先把 initializer 全转换成 constant op，调用 onnx version converter 换好 opset 之后，再将 constant op 转回 initializer

我刚翻了下 onnx 的 issue，当时没解决的问题在今年 1 月底解决合进主线了，最新的 onnx 应该就没有这个问题了：

https://github.com/onnx/onnx/issues/4060
https://github.com/onnx/onnx/issues/4102

建议考虑将 onnx 升级到 1.11 版本以上，然后直接用 onnx 官方的 version converter 再试试：

```
import onnx
from onnx import version_converter
model = onnx.load('model.onnx')
new_model = version_converter.convert_version(model, 12)
```
