### ISSUE TITLE
Model in onnx model zoo can not run in ppl.nn

### ISSUE THREAD

**Issue by zerollzeng** [openppl-public/ppl.nn#5]
Hi folks. I tried running models from onnx model zoo and find out a lots of pretrained model can not run with ppl.nn, the error is varies across models, eg

```
./pplnn-build/tools/pplnn --onnx-model resnet50-v1-7.onnx
[INFO][2021-07-04 04:43:10.810][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
[WARNING][2021-07-04 04:43:12.138][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
[INFO][2021-07-04 04:43:12.138][pplnn.cc:88] ***** register CudaEngine *****
[ERROR][2021-07-04 04:43:12.211][model_parser.cc:46] unsupported opset [:8]
[ERROR][2021-07-04 04:43:12.214][runtime_builder_impl.cc:33] parse graph failed: unsupported
[ERROR][2021-07-04 04:43:12.214][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-04 04:43:12.219][pplnn.cc:697] create OnnxRuntimeBuilder failed.

or

./pplnn-build/tools/pplnn --onnx-model efficientnet-lite4-11.onnx
[INFO][2021-07-04 04:40:22.270][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
[WARNING][2021-07-04 04:40:23.590][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
[INFO][2021-07-04 04:40:23.590][pplnn.cc:88] ***** register CudaEngine *****
[ERROR][2021-07-04 04:40:24.453][simple_graph_partitioner.cc:73] cannot find implementation of op[:MatMul]
[ERROR][2021-07-04 04:40:24.453][utils.cc:412] partitioning graph[tf2onnx] failed: not found
[ERROR][2021-07-04 04:40:24.453][runtime_builder_impl.cc:39] process graph failed: not found
[ERROR][2021-07-04 04:40:24.453][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: not found
[ERROR][2021-07-04 04:40:24.455][pplnn.cc:697] create OnnxRuntimeBuilder failed.

...

```

how's the restriction with onnx and do you have a support matrix about the operators?

**Comment by openppl-public** [comment]
> Hi folks. I tried running models from onnx model zoo and find out a lots of pretrained model can not run with ppl.nn, the error is varies across models, eg
> 
> ```
> ./pplnn-build/tools/pplnn --onnx-model resnet50-v1-7.onnx
> [INFO][2021-07-04 04:43:10.810][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
> [WARNING][2021-07-04 04:43:12.138][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
> [INFO][2021-07-04 04:43:12.138][pplnn.cc:88] ***** register CudaEngine *****
> [ERROR][2021-07-04 04:43:12.211][model_parser.cc:46] unsupported opset [:8]
> [ERROR][2021-07-04 04:43:12.214][runtime_builder_impl.cc:33] parse graph failed: unsupported
> [ERROR][2021-07-04 04:43:12.214][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: unsupported
> [ERROR][2021-07-04 04:43:12.219][pplnn.cc:697] create OnnxRuntimeBuilder failed.
> 


> or
> 
> ./pplnn-build/tools/pplnn --onnx-model efficientnet-lite4-11.onnx
> [INFO][2021-07-04 04:40:22.270][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
> [WARNING][2021-07-04 04:40:23.590][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
> [INFO][2021-07-04 04:40:23.590][pplnn.cc:88] ***** register CudaEngine *****
> [ERROR][2021-07-04 04:40:24.453][simple_graph_partitioner.cc:73] cannot find implementation of op[:MatMul]
> [ERROR][2021-07-04 04:40:24.453][utils.cc:412] partitioning graph[tf2onnx] failed: not found
> [ERROR][2021-07-04 04:40:24.453][runtime_builder_impl.cc:39] process graph failed: not found
> [ERROR][2021-07-04 04:40:24.453][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: not found
> [ERROR][2021-07-04 04:40:24.455][pplnn.cc:697] create OnnxRuntimeBuilder failed.
> 
> ...
> ```
> 
> how's the restriction with onnx and do you have a support matrix about the operators?



> Hi folks. I tried running models from onnx model zoo and find out a lots of pretrained model can not run with ppl.nn, the error is varies across models, eg
> 
> ```
> ./pplnn-build/tools/pplnn --onnx-model resnet50-v1-7.onnx
> [INFO][2021-07-04 04:43:10.810][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
> [WARNING][2021-07-04 04:43:12.138][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
> [INFO][2021-07-04 04:43:12.138][pplnn.cc:88] ***** register CudaEngine *****
> [ERROR][2021-07-04 04:43:12.211][model_parser.cc:46] unsupported opset [:8]
> [ERROR][2021-07-04 04:43:12.214][runtime_builder_impl.cc:33] parse graph failed: unsupported
> [ERROR][2021-07-04 04:43:12.214][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: unsupported
> [ERROR][2021-07-04 04:43:12.219][pplnn.cc:697] create OnnxRuntimeBuilder failed.
> 
> or
> 
> ./pplnn-build/tools/pplnn --onnx-model efficientnet-lite4-11.onnx
> [INFO][2021-07-04 04:40:22.270][pplnn.cc:683] ppl.nn version: v0.1.0-dirty
> [WARNING][2021-07-04 04:40:23.590][engine.cc:192] Default input dims for dynamic graph are 1_3_224_224, we recommend using '--dims' to set a suitable training shape.
> [INFO][2021-07-04 04:40:23.590][pplnn.cc:88] ***** register CudaEngine *****
> [ERROR][2021-07-04 04:40:24.453][simple_graph_partitioner.cc:73] cannot find implementation of op[:MatMul]
> [ERROR][2021-07-04 04:40:24.453][utils.cc:412] partitioning graph[tf2onnx] failed: not found
> [ERROR][2021-07-04 04:40:24.453][runtime_builder_impl.cc:39] process graph failed: not found
> [ERROR][2021-07-04 04:40:24.453][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: not found
> [ERROR][2021-07-04 04:40:24.455][pplnn.cc:697] create OnnxRuntimeBuilder failed.
> 
> ...
> ```
> 
> how's the restriction with onnx and do you have a support matrix about the operators?

Currently PPLNN supports opset >=11 and MatMul is not supported in CUDA version. You can find supported ops and versions [here](docs/en/supported-ops-and-platforms.md).

**Comment by codgeek** [comment]
it seems lots of newest pre-trained model in onnx zoo cannot work on ppl.  I've tried `mobilenetv2-7.onnx` `resnet50-v2-7.onnx` `squeezenet1.0-9.onnx`.  all of them failed because of opset.   do ppl have tools to convert them?

```
./pplnn-build/tools/pplnn --onnx-model onnx/mobilenetv2-7.onnx
[INFO][2021-07-05 20:40:29.406][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8
[INFO][2021-07-05 20:40:29.406][pplnn.cc:110] ***** register X86Engine *****
[ERROR][2021-07-05 20:40:29.412][model_parser.cc:46] unsupported opset [:10]
[ERROR][2021-07-05 20:40:29.413][runtime_builder_impl.cc:33] parse graph failed: unsupported
[ERROR][2021-07-05 20:40:29.413][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: unsupported
[ERROR][2021-07-05 20:40:29.414][pplnn.cc:697] create OnnxRuntimeBuilder failed.
```

**Comment by openppl-public** [comment]
> it seems lots of newest pre-trained model in onnx zoo cannot work on ppl. I've tried `mobilenetv2-7.onnx` `resnet50-v2-7.onnx` `squeezenet1.0-9.onnx`. all of them failed because of opset. do ppl have tools to convert them?
> 
> ```
> ./pplnn-build/tools/pplnn --onnx-model onnx/mobilenetv2-7.onnx
> [INFO][2021-07-05 20:40:29.406][pplnn.cc:683] ppl.nn version: 7dd75a1077867fc9a762449953417088446ae2f8
> [INFO][2021-07-05 20:40:29.406][pplnn.cc:110] ***** register X86Engine *****
> [ERROR][2021-07-05 20:40:29.412][model_parser.cc:46] unsupported opset [:10]
> [ERROR][2021-07-05 20:40:29.413][runtime_builder_impl.cc:33] parse graph failed: unsupported
> [ERROR][2021-07-05 20:40:29.413][onnx_runtime_builder_factory.cc:42] init OnnxRuntimeBuilder failed: unsupported
> [ERROR][2021-07-05 20:40:29.414][pplnn.cc:697] create OnnxRuntimeBuilder failed.
> ```

There is a converter tool provided by the official ONNX team: https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md. May it helps.

**Comment by zerollzeng** [comment]
Thanks, I think there is some workaround to solve this.

Closed
