### ISSUE TITLE
ppl.nn是通过看哪个结果数据来衡量被测服务器CPU的性能的？

### ISSUE THREAD

**Issue by CodeDance364** [openppl-public/ppl.nn#531]
想用ppl.nn作为benchmark来测服务器CPU性能，有几个问题：
1. ppl.nn是通过看哪个结果数据来衡量被测服务器CPU的性能的？结果数据怎么解读？
2. build.sh编译时可否支持-DPPLNN_USE_ARMV9=ON
3. 有什么办法能控制input的dim(s): 1 3 630 160这四个参数值？想指定这几个参数来控制运算量大小

**Comment by ZichenTian** [comment]
1. ppl.nn 是通过测试网络整体的耗时，来横向对比服务器之间的性能差异
2. 目前尚未支持 armv9，我们会在后续开发过程中逐步支持
3. pplnn 工具的 --in-shapes 选项可以改变输入 shape，具体用法可以 ./pplnn --help 查看

**Comment by CodeDance364** [comment]
1. 统一识别到terminal打印中耗时相关的有这么些结果参数：
    Prepare costs
    Run() costs
    Total duaration
    Conv AVG_TIME
    Gem AVG_TIME
    Reduce mean AVG_TIME
    PM.recorder AVG_TIME
    RUN COUNT
    AVG KERNEL TIME
    AVG RUN TIME
    TOT KERNEL TIME
    TOT RUN TIME
    
请问下横向对比服务器性能差异，用哪几个参数能比较科学的衡量？另外，结果数据的解读，哪里有统一的说明吗？
2. armv9支持有大概计划时间点吗？
