### ISSUE TITLE
pplnn test tool run error

### ISSUE THREAD

**Issue by xizi** [openppl-public/ppl.nn#532]
CentOS 7.6.1810
CUDA 11.0
run "./pplnn-build/tools/pplnn --use-cuda --onnx-model tests/testdata/conv.onnx" meet an error
<img width="1117" alt="截屏2022-05-29 21 52 36" src="https://user-images.githubusercontent.com/3853150/170872774-550f87e1-a74e-4df1-ac9b-30a4804ebfbc.png">

**Comment by xizi** [comment]
run "python3 ./tools/pplnn.py --use-cuda --onnx-model tests/testdata/conv.onnx" is ok
<img width="1037" alt="截屏2022-05-30 11 41 49" src="https://user-images.githubusercontent.com/3853150/170913187-ed9072e4-d46c-42d5-80a4-e7f899f75235.png">

**Comment by ouonline** [comment]
> run "python3 ./tools/pplnn.py --use-cuda --onnx-model tests/testdata/conv.onnx" is ok <img alt="截屏2022-05-30 11 41 49" width="1037" src="https://user-images.githubusercontent.com/3853150/170913187-ed9072e4-d46c-42d5-80a4-e7f899f75235.png">

We can not find the commit `d495adcecf...` in the master branch. Please update to the latest version and try again.

**Comment by xizi** [comment]
<img width="1072" alt="截屏2022-05-30 14 19 43" src="https://user-images.githubusercontent.com/3853150/170929311-d4e1e0c3-dedc-4f94-976b-7c70569ebb18.png">
meet same error

**Comment by ouonline** [comment]
Did you run ppl.nn on a virtual machine? Please add `--mm-policy perf` and try again:

```bash
./pplnn-build/tools/pplnn --use-cuda --onnx-model tests/testdata/conv.onnx --mm-policy perf
```

**Comment by xizi** [comment]
<img width="1412" alt="截屏2022-05-30 14 54 58" src="https://user-images.githubusercontent.com/3853150/170934282-154e93bd-6514-4b2f-8d24-6932e5064827.png">
