### ISSUE TITLE
ppl无法使用多batch

### ISSUE THREAD

**Issue by Beichen-Wang** [openppl-public/ppl.nn#539]
## What are the problems?(screenshots or detailed error messages)

./ppl.nn/build/tools/pplnn --enable-profiling --warmup-iterations 10 --use-cuda --onnx-model resnet50.onnx --kernel-type INT8 --in-shapes 32_3_224_224
无法运行成功，加入--quick-select 可以 但是速度较慢

## Which version(commit id or tag) of ppl.nn is used?
 
最新的commit

## What are the commands used to build ppl.nn?

cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DPPLNN_USE_CUDA=ON -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_USE_X86_64=ON  -DPPLNN_USE_OPENMP=ON

**Comment by Si-XU** [comment]
问题已修复，是选算法时分块开的太大了
