### ISSUE TITLE
Will ppl.nn x86 support int8 inference?

### ISSUE THREAD

**Issue by shiwenloong** [openppl-public/ppl.nn#56]
As can be seen in [openvino benchmark](https://docs.openvinotoolkit.org/2020.4/openvino_docs_performance_benchmarks.html), int8 inference achieves better performance than fp32 on intel CPU. Will ppl.nn x86 support int8 inference?

**Comment by Alcanderian** [comment]
ppl.nn x86 is planning to support more feature(a very long list), including vnni int8 inference.
