### ISSUE TITLE
linux平台编译问题

### ISSUE THREAD

**Issue by liuqiaoping7** [openppl-public/ppl.nn#6]
pplnn tlinux build.sh遇到的问题：
1. pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/simd_tools.cpp:15:45: 错误：‘_MM_DENORMALS_ZERO_ON’在此作用域中尚未声明
2. from /home/shiweifan/qiao/pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/arithmetic/sse/arithmetic_fp32_sse.cpp:1:
    /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/nmmintrin.h:31:3: 错误：#error "SSE4.2 instruction set not enabled"
修改cmakelist.txt:
if(CMAKE_COMPILER_IS_GNUCXX)
    add_compile_options(-msse4.2)
    message(STATUS "optional:-msse4.2")   
endif(CMAKE_COMPILER_IS_GNUCXX)
遇到的问题：
Building CXX object src/ppl/nn/engines/x86/impls/CMakeFiles/PPLKernelX86.dir/src/ppl/kernel/x86/fp32/arithmetic/avx/arithmetic_fp32_avx.cpp.o
c++: 错误：unrecognized command line option ‘-mtune-ctrl=256_unaligned_load_optimal,256_unaligned_store_optimal’
咨询一下可有类似问题，如何解决。

**Comment by openppl-public** [comment]
> pplnn tlinux build.sh遇到的问题：
> 
> 1. pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/simd_tools.cpp:15:45: 错误：‘_MM_DENORMALS_ZERO_ON’在此作用域中尚未声明
> 2. from /home/shiweifan/qiao/pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/arithmetic/sse/arithmetic_fp32_sse.cpp:1:
>    /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/nmmintrin.h:31:3: 错误：#error "SSE4.2 instruction set not enabled"
>    修改cmakelist.txt:
>    if(CMAKE_COMPILER_IS_GNUCXX)
>    add_compile_options(-msse4.2)
>    message(STATUS "optional:-msse4.2")
>    endif(CMAKE_COMPILER_IS_GNUCXX)
>    遇到的问题：
>    Building CXX object src/ppl/nn/engines/x86/impls/CMakeFiles/PPLKernelX86.dir/src/ppl/kernel/x86/fp32/arithmetic/avx/arithmetic_fp32_avx.cpp.o
>    c++: 错误：unrecognized command line option ‘-mtune-ctrl=256_unaligned_load_optimal,256_unaligned_store_optimal’
>    咨询一下可有类似问题，如何解决。

所用的 gcc 版本是？

**Comment by liuqiaoping7** [comment]
> > pplnn tlinux build.sh遇到的问题：
> > 
> > 1. pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/simd_tools.cpp:15:45: 错误：‘_MM_DENORMALS_ZERO_ON’在此作用域中尚未声明
> > 2. from /home/shiweifan/qiao/pplnn_cpu/src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/arithmetic/sse/arithmetic_fp32_sse.cpp:1:
> >    /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/nmmintrin.h:31:3: 错误：#error "SSE4.2 instruction set not enabled"
> >    修改cmakelist.txt:
> >    if(CMAKE_COMPILER_IS_GNUCXX)
> >    add_compile_options(-msse4.2)
> >    message(STATUS "optional:-msse4.2")
> >    endif(CMAKE_COMPILER_IS_GNUCXX)
> >    遇到的问题：
> >    Building CXX object src/ppl/nn/engines/x86/impls/CMakeFiles/PPLKernelX86.dir/src/ppl/kernel/x86/fp32/arithmetic/avx/arithmetic_fp32_avx.cpp.o
> >    c++: 错误：unrecognized command line option ‘-mtune-ctrl=256_unaligned_load_optimal,256_unaligned_store_optimal’
> >    咨询一下可有类似问题，如何解决。
> 
> 所用的 gcc 版本是？

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright © 2015 Free Software Foundation, Inc.
您好，低于4.9就会出现上述问题吗

**Comment by openppl-public** [comment]
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
> Copyright © 2015 Free Software Foundation, Inc.
> 您好，低于4.9就会出现上述问题吗

是的，请参考 https://github.com/openppl-public/ppl.nn/blob/master/docs/en/building-from-source.md 这个文档安装所需的依赖。
