### ISSUE TITLE
【gemm_fp32_fma performance】常用shape下，gemm_fp32_fma和tensorflow1.15  eigen matmul性能几乎持平?

### ISSUE THREAD

**Issue by huangmiumang** [openppl-public/ppl.nn#619]
问题：测试sgemm时，发现openppl的gemm_fp32_fma在一些常用shape下和tensorflow1.15 eigen matmul性能几乎持平，符合预期吗？有啥办法提升吗？ 
相关参数: openppl版本v0.8，intel 32核机器，均使用多线程，build命令：./build.sh -DPPLNN_USE_X86_64=ON -DPPLNN_ENABLE_ONNX_MODEL=OFF -DPPL_USE_X86_OMP=ON -DPPLNN_USE_OPENMP=ON
以下是测试数据:
![image](https://user-images.githubusercontent.com/19187765/179381949-32bb51de-b3b2-477a-84b5-755405bfdfa1.png)

**Comment by Alcanderian** [comment]
您好，请给出具体的CPU型号，线程数，操作系统，编译工具链等环境要素才能够估计出速度是否合理。
以及测试速度的方法也是非常影响结果的

目前看来您提供的数据比我们在linux下用测试工具测出来的单线程速度要慢的多，比我们测试的多线程（16线程）结果慢了10倍还不止，先提供上面的信息给我们会更好。


===============================================================


我们有提供测试用的小工具：https://github.com/openppl-public/ppl.nn/blob/master/src/ppl/nn/engines/x86/impls/test/test_gemm.cpp
可以在build目录下的`src/ppl/nn/engines/x86/impls/`文件夹找到`test_gemm`
具体的cfg文件可以这样写：
```
m150n128k256_n0
m150n256k512_n0
```
测试命令行: `OMP_NUM_THREADS=1 ./test_gemm -cfg ./cfg -isa fma`


===============================================================


单纯从代码的角度讲，目前`gemm_fp32_fma`只针对大矩阵做优化，暂时没对小矩阵做优化，还有一点牙膏可以挤一挤。
如果B矩阵可以预处理的话，可以使用
https://github.com/openppl-public/ppl.nn/blob/master/src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/gemm.h#L31
下的`gemm_fp32_pack_b`函数预处理B矩阵
之后调用`gemm_fp32_fma`时使`typeB=PACKED`可以进一步提升速度
测试命令行: `OMP_NUM_THREADS=1 ./test_gemm -cfg ./cfg -isa fma -type_b 2`

**Comment by huangmiumang** [comment]
> 
您好，谢谢您的解答，补充的测试数据如下：
cpu型号: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
线程数:32
操作系统: CentOS Linux release 7.5.1804
numa节点数:2
openppl版本:v0.8
编译工具链：gcc82，编译命令: ./build.sh -DPPLNN_USE_X86_64=ON -DPPLNN_ENABLE_ONNX_MODEL=OFF -DPPL_USE_X86_OMP=ON -DPPLNN_USE_OPENMP=ON
耗时是利用tensorflow的timeline工具，除了上面这些k=256、512的情况，其他一些不规则的k情况下，ppl的耗时优势还是比较明显的，**所以疑问点在于k为256、512等一些shape下，ppl和tensorflow1.15 eigen matmul性能基本持平？**
不同shape测试结果，线程数都是32:
![image](https://user-images.githubusercontent.com/19187765/179475616-164458ed-d987-44f9-8ace-5d1993420720.png)

以下是使用ppl的相关代码片段：
![image](https://user-images.githubusercontent.com/19187765/179476659-01e913ae-02ef-4820-b461-29ccb2f608de.png)

本地test_gemm 测试情况如下：
测试命令:OMP_NUM_THREADS=16 ./test_gemm -cfg ./cfg -isa fma
分别为0.028ms和0.053ms左右，这个应该和您那边测试差不多
![image](https://user-images.githubusercontent.com/19187765/179475920-d05ca310-194e-4bb4-8620-b794be88eb84.png)

**Comment by Alcanderian** [comment]
请问用tensorflow进行测试的时候，重复测试了多少次呢？
test_gemm里面默认对每一个case进行至少1秒钟的压测

如果你把配置重复多次（示例在下方）
然后使用`OMP_NUM_THREADS=32 ./test_gemm -cfg ./cfg -isa fma -min_iter 1 -min_second 0 -warm_up 0`
会看到速度在慢慢收敛的，如果测试次数过少，性能会受到热机情况的影响

**因此我这边比较建议的测速方法是让程序跑足够的时间而不是只看跑的次数**

可以试试调整tensorflow的测试方法
可以和test_gemm默认一样进行压测，也可以用非压测的方式（带`-min_iter 1 -min_second 0 -warm_up 0`的test_gemm）
两者测试方法保持一致之后，才可以**控制变量**，如果速度差异比较大，就可以考虑tensorflow是否引入了一些别的开销了


另外就是，看test_gemm的测试结果，感觉这台机子的内存带宽偏弱了？
我用一台2NUMA的Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz测了一下
`m150n128k256` 0.021ms
`m150n256k512` 0.050ms
两台机器的CPU是比较相似的，基频只相差0.1GHz，`m150n128k256`差了30%说明别的硬件上有些差异

示例配置
```
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
m150n128k256_n0
```

**Comment by huangmiumang** [comment]
> 
1. 使用tensorflow测试30次，应该不会是tensorflow warmup的问题。
2. 测试结果是在一些shape上正向，一些shape上是负向，这些shape刚好是对应的k是256、512，应该不会tensorflow是其他开销的问题吧。
3. 另外，用以下打点的方法测试出来的耗时和表中差不多。
![image](https://user-images.githubusercontent.com/19187765/179679360-11c52b77-44dd-4315-aa14-1f4d37ea241e.png)

**Comment by Alcanderian** [comment]
那要不先用`OMP_NUM_THREADS=32 ./test_gemm -cfg ./cfg -isa fma -min_iter 1 -min_second 0 -warm_up 0`和重复配置测试比较一下，现在没有对比无法得出有意义的结论

**Comment by huangmiumang** [comment]
> 
1. OMP_NUM_THREADS=32 ./test_gemm -cfg ./cfg -isa fma -min_iter 1 -min_second 0 -warm_up 0 运行结果如下
![image](https://user-images.githubusercontent.com/19187765/179681828-38b322c3-c036-4185-906c-5bf256f56f00.png)
2. 重复配置测试结果应该之前贴

**Comment by Alcanderian** [comment]
tensorflow上的压测速度和test_gemm下的非压测结果比较接近，而与test_gemm压测速度相差甚远
那估计还是tensorflow导致了一些额外开销
这些开销不是显式的，而是体现在内存分配，任务调度，资源使用上，需要系统性地看待

test_gemm的非压测流程是
1. 分配矩阵内存
2. 生成随机数据
3. 进行一次测速
4. 释放内存

压测流程是
1. 分配矩阵内存
2. 生成随机数据
3. 进行多次测速
4. 释放内存

OMP_NUM_THREADS=32 ./test_gemm -cfg ./cfg -isa fma -min_iter 1 -min_second 0 -warm_up 0
我这边的测试结果是，这么看硬件上也有一些小问题
```
%line_no,%case_string,%min_ms,%max_gflops,%max_gbps,%avg_ms,%avg_gflops,%avg_gbps
1,m150n128k256_n0,1.431,6.87,0.25,1.431,6.87,0.25
2,m150n128k256_n0,0.110,89.13,3.28,0.110,89.13,3.28
3,m150n128k256_n0,0.241,40.80,1.50,0.241,40.80,1.50
4,m150n128k256_n0,0.208,47.35,1.74,0.208,47.35,1.74
5,m150n128k256_n0,0.198,49.76,1.83,0.198,49.76,1.83
6,m150n128k256_n0,0.376,26.12,0.96,0.376,26.12,0.96
7,m150n128k256_n0,0.275,35.77,1.32,0.275,35.77,1.32
8,m150n128k256_n0,0.238,41.31,1.52,0.238,41.31,1.52
9,m150n128k256_n0,0.248,39.60,1.46,0.248,39.60,1.46
10,m150n128k256_n0,0.247,39.78,1.46,0.247,39.78,1.46
11,m150n128k256_n0,0.245,40.04,1.47,0.245,40.04,1.47
12,m150n128k256_n0,0.216,45.46,1.67,0.216,45.46,1.67
13,m150n128k256_n0,0.230,42.70,1.57,0.230,42.70,1.57
14,m150n128k256_n0,0.252,39.03,1.44,0.252,39.03,1.44
15,m150n128k256_n0,0.240,40.88,1.50,0.240,40.88,1.50
16,m150n128k256_n0,0.256,38.42,1.41,0.256,38.42,1.41
17,m150n128k256_n0,0.183,53.75,1.98,0.183,53.75,1.98
18,m150n128k256_n0,0.072,136.15,5.01,0.072,136.15,5.01
19,m150n128k256_n0,0.066,149.17,5.49,0.066,149.17,5.49
20,m150n128k256_n0,0.069,142.62,5.24,0.069,142.62,5.24
21,m150n128k256_n0,0.072,136.48,5.02,0.072,136.48,5.02
22,m150n128k256_n0,0.070,141.36,5.20,0.070,141.36,5.20
23,m150n128k256_n0,0.068,145.55,5.35,0.068,145.55,5.35
24,m150n128k256_n0,0.076,128.89,4.74,0.076,128.89,4.74
25,m150n128k256_n0,0.078,126.77,4.66,0.078,126.77,4.66
26,m150n128k256_n0,0.076,129.88,4.78,0.076,129.88,4.78
27,m150n128k256_n0,0.068,144.60,5.32,0.068,144.60,5.32
28,m150n128k256_n0,0.069,143.04,5.26,0.069,143.04,5.26
29,m150n128k256_n0,0.076,130.10,4.78,0.076,130.10,4.78
30,m150n128k256_n0,0.070,140.35,5.16,0.070,140.35,5.16
31,m150n128k256_n0,0.070,141.05,5.19,0.070,141.05,5.19
32,m150n128k256_n0,0.068,143.69,5.28,0.068,143.69,5.28
33,m150n128k256_n0,0.075,130.49,4.80,0.075,130.49,4.80
34,m150n128k256_n0,0.065,150.90,5.55,0.065,150.90,5.55
35,m150n128k256_n0,0.065,151.85,5.58,0.065,151.85,5.58
36,m150n128k256_n0,0.078,125.69,4.62,0.078,125.69,4.62
37,m150n128k256_n0,0.074,132.68,4.88,0.074,132.68,4.88
38,m150n128k256_n0,0.068,145.35,5.34,0.068,145.35,5.34
39,m150n128k256_n0,0.071,138.39,5.09,0.071,138.39,5.09
40,m150n128k256_n0,0.068,144.52,5.31,0.068,144.52,5.31
41,m150n128k256_n0,0.069,141.85,5.22,0.069,141.85,5.22
42,m150n128k256_n0,0.069,142.21,5.23,0.069,142.21,5.23
43,m150n128k256_n0,0.069,142.42,5.24,0.069,142.42,5.24
44,m150n128k256_n0,0.068,143.89,5.29,0.068,143.89,5.29
45,m150n128k256_n0,0.079,124.62,4.58,0.079,124.62,4.58
46,m150n128k256_n0,0.075,130.81,4.81,0.075,130.81,4.81
47,m150n128k256_n0,0.078,126.56,4.65,0.078,126.56,4.65
tot time(ms): 7.33313   avg gflops: 103.589     avg gbps: 3.80904
```

**Comment by huangmiumang** [comment]
>
1. 咱们的opennppl gemm有和其他常见开源的cpu gemm的性能对比吗，比如和eigen、openblase、mkl？

**Comment by Alcanderian** [comment]
eigen没有比过
和openblas比较过，大矩阵和小矩阵都有优势，单线程/多线程上也有优势
和mkl比，都有一些小差距，我比较菜，代码写的也比较简陋，欢迎大佬们来指点迷津
和onednn进行过对比，小矩阵/超小矩阵上没有用特别的kernel优化，有一点差距，主要体现在多线程；大矩阵上基本持平，部分case互有胜负
