### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by pangr** [openppl-public/ppl.nn#689]
## What are the problems?(screenshots or detailed error messages)
![image](https://user-images.githubusercontent.com/5838111/188805210-16592ba7-61df-48cc-b8f7-ef02f55bedbd.png)

## What are the types of GPU/CPU you are using?
GPU 1080ti
## What's the operating system ppl.nn runs on?
ubuntu 18
## Which version(commit id or tag) of ppl.nn is used?
master
## What are the commands used to build ppl.nn?
./build.sh -DPPLNN_USE_X86_64=ON -DPPLNN_USE_CUDA=ON -DPPLNN_ENABLE_PYTHON_API=ON
## models and inputs for reproducing these problems (send them to openppl.ai@hotmail.com if necessary)
resnet152

**Comment by Si-XU** [comment]
OpenPPL CUDA only support Turing and Ampere arch right now. 1080ti is not supported.
