### ISSUE TITLE
Onnx run error

### ISSUE THREAD

**Issue by XuMicoder** [openppl-public/ppl.nn#697]
## What are the problems?(screenshots or detailed error messages)
![image](https://user-images.githubusercontent.com/80387578/190912175-c046c700-646b-4197-a3c6-1a49d48e3eb0.png)
image preprocess succeed!
[INFO][2022-09-18 22:27:35.468][utils.cc:456] total partition(s) of graph[torch-jit-export]: 1.
successfully create runtime builder!
successfully build runtime!
successfully set input data to tensor [x.1]!
[ERROR][2022-09-18 22:27:37.401][kernel.cc:31] reshape kernel[Slice_1464] failed: invalid value
[ERROR][2022-09-18 22:27:37.402][kernel.cc:55] BeforeExecute() of kernel[Slice_1464] failed: invalid value
[ERROR][2022-09-18 22:27:37.402][sequential_scheduler.cc:135] exec kernel[Slice_1464] of type[:Slice:11] failed: invalid value
[ERROR][2022-09-18 22:27:37.402][runtime_impl.cc:342] Run() failed: invalid value
## What are the types of GPU/CPU you are using?
cpu x86
## What's the operating system ppl.nn runs on?
win11
## What's the compiler and its version?
msvc
## Which version(commit id or tag) of ppl.nn is used?
the newleast
## What are the commands used to build ppl.nn?
vs2019
## models and inputs for reproducing these problems (send them to openppl.ai@hotmail.com if necessary)
swin-transformer-seg

**Comment by XuMicoder** [comment]
python环境下使用onnxruntime推理可以输出正常结果，但是c++调用ppl.nn的api加载推理出现该报错

**Comment by Alcanderian** [comment]
可以编译一个debug版本的ppl.nn，看看具体的LOG
