### ISSUE TITLE
Why Winograd 4x3 use 6 x 2 register blocking not 4 x 3 register blocking in PPL

### ISSUE THREAD

**Issue by llxingkongxia** [openppl-public/ppl.nn#7]
As the title describe,  why winograd not use 4x3 reigster blocking ?
#define TILE_RF_CNT() 6
#define OC_RF_CNT()  2

Thanks.

**Comment by Alcanderian** [comment]
FMA implement of PPLNN is currently using NcHW16C DataLayout which 4x3 register blocking is not compatible with it :)
