### ISSUE TITLE
malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by 111qqz** [openppl-public/ppl.nn#797]
# 问题
跑python demo时遇到如下问题
![image](https://user-images.githubusercontent.com/30498101/216872105-5f549513-e4fb-4454-8ef3-b4b9848ed8b9.png)

# 复现环境
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
cmake version 3.22.1
git version 2.34.1
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux

```shell
PYTHONPATH=./pplnn-build/install/lib python3 ./tools/pplnn.py --use-x86 --onnx-model tests/testdata/conv.onnx
```

**Comment by ouonline** [comment]
please update to the latest `master` and try again. https://github.com/openppl-public/ppl.nn/commit/1a4acf6d68086b36a8538656887a7fa87edc8613 fixed this problem.

**Comment by 111qqz** [comment]
it works. thanks!
