### ISSUE TITLE
如何使用cmake的将ppl.nn和依赖ppl.nn的代码一同编译？

### ISSUE THREAD

**Issue by 111qqz** [openppl-public/ppl.nn#800]
我先编译ppl.nn,然后make install到某个路径
之后按照 https://github.com/openppl-public/ppl.nn/issues/358 提到的使用find_package的方法是没问题的

想请教下，我想合并这两个步骤
目前使用cmake 的FetchContent把ppl.nn作为依赖项拉下来  但是target_link_libraries 时不知道要怎么写ppl的target name

**Comment by ouonline** [comment]
https://github.com/openppl-public/ppl.nn/blob/master/docs/en/how-to-integrate.md#2-using-pplnn-as-a-source-dependency

**Comment by ouonline** [comment]
> 想请教下，我想合并这两个步骤 目前使用cmake 的FetchContent把ppl.nn作为依赖项拉下来 但是target_link_libraries 时不知道要怎么写ppl的target name

target_link_libraries(<your-target> PRIVATE pplnn_static)

refer to: https://github.com/openppl-public/ppl.nn/blob/master/CMakeLists.txt#L59

**Comment by 111qqz** [comment]
感谢，解决了
