### ISSUE TITLE
 Segmentation fault at ppl::nn::x86::X86Kernel::DumpOutputTensors

### ISSUE THREAD

**Issue by 111qqz** [openppl-public/ppl.nn#805]
## What are the problems?(screenshots or detailed error messages)
![image](https://user-images.githubusercontent.com/30498101/219251220-5b5248d5-d6a9-4d60-84bd-499aedafecff.png)

## What are the types of GPU/CPU you are using?

cpu

## What's the operating system ppl.nn runs on?
CentOS Linux release 7.7.1908 (Core)

## What's the compiler and its version?
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

## Which version(commit id or tag) of ppl.nn is used?

[5b57da0](https://github.com/openppl-public/ppl.nn/commit/5b57da0b555ae2125c1626cc29aa314f1b61775b)
## What are the commands used to build ppl.nn?

./build.sh -DPPLNN_USE_X86_64=ON

问题描述:
当只跑单个模型的时候，不会出现问题
当运行多个1个模型的时候，会稳定core

我的做法是，每个模型对应了一个 ppl::nn::Runtime  ，关键代码如下
model_impl.h

```c++
class PPLModelImpl {
 public:
  Status Init(const std::string& model_path);

  std::vector<float> Run(const std::vector<float> input);

 private:
// 设置runtime的input
  bool SetInputs(const std::vector<float>& buffer, ppl::nn::Runtime* runtime);

 private:
  std::unique_ptr<ppl::nn::Runtime> runtime_;
};

```

model_impl.cpp

```c++
Status PPLModelImpl::Init(const std::string& model_path) {
  // 设置一些engine
  logi("Init ppl engine for model {}", model_path);
  // 1-> info
  GetCurrentLogger()->SetLogLevel(1);
  // TODO: options 可配置
  ppl::nn::x86::EngineOptions options;
  options.mm_policy = ppl::nn::x86::MM_MRU;

  auto x86_engine = ppl::nn::x86::EngineFactory::Create(options);
  auto rc = x86_engine->Configure(ppl::nn::x86::ENGINE_CONF_GRAPH_FUSION, 1);
  if (ppl::common::RC_SUCCESS != rc) {
    loge("x86_engine Configure ENGINE_CONF_GRAPH_FUSION failed\n");
    return Status(wyai::eNotReady);
  }
  //   ppl::kernel::x86::set_omp_core_binding(nullptr, 0, 1);
  //   ppl::kernel::x86::set_omp_num_threads(1);

  std::vector<std::unique_ptr<ppl::nn::Engine>> engines;
  engines.emplace_back(std::unique_ptr<ppl::nn::Engine>(x86_engine));

  auto builder = std::unique_ptr<onnx::RuntimeBuilder>(ppl::nn::onnx::RuntimeBuilderFactory::Create());
  if (!builder) {
    loge("x86_engine Configure ENGINE_CONF_GRAPH_FUSION failed\n");
    return Status(wyai::eNotReady);
  }
  auto status = builder->LoadModel(model_path.c_str());
  if (status != RC_SUCCESS) {
    loge("init OnnxRuntimeBuilder failed:{}\n", status);
    return Status(wyai::eNotReady);
  }

  std::vector<Engine*> engine_ptrs(engines.size());
  for (uint32_t i = 0; i < engines.size(); ++i) {
    engine_ptrs[i] = engines[i].get();
  }
  onnx::RuntimeBuilder::Resources resources;
  resources.engines = engine_ptrs.data();
  resources.engine_num = engine_ptrs.size();

  status = builder->SetResources(resources);
  if (status != RC_SUCCESS) {
    loge("onnx RuntimeBuilder SetResources failed: {}\n", status);
    return Status(wyai::eNotReady);
  }

  status = builder->Preprocess();
  if (status != RC_SUCCESS) {
    loge("builder preprocess failed: : {}\n", status);
    // TODO: better error code
    return Status(wyai::eNotReady);
    // return -1;
  }

  auto runtime = std::unique_ptr<Runtime>(builder->CreateRuntime());
  // std::unique_ptr<Runtime> runtime;
  // runtime.reset(builder->CreateRuntime());
  if (!runtime) {
    loge("CreateRuntime failed.\n", status);
    return Status(wyai::eNotReady);
  }
  runtime_ = std::move(runtime);
  input_size_ = PrepareModelInputSize();
  return Status(wyai::eSuccess);
}

```
是否是哪里的使用方式不正确？

**Comment by 111qqz** [comment]
另一种可能的bt


![image](https://user-images.githubusercontent.com/30498101/219261113-f03a1e21-91b0-4ef6-8e7b-36f65d172407.png)

**Comment by Alcanderian** [comment]
出现这个错误可能是因为这些模型的Tensor名字和大小都相同，Dump接口同时写入这个文件导致冲突
Dump文件的命名规则https://github.com/openppl-public/ppl.nn/blob/master/src/ppl/nn/engines/x86/kernel.cc#L79

DumpDebugTensor一般只建议在单模型debug中间tensor的时候使用
- 先排查出输出错误的模型
- dump出模型相应的输入输出数据
- 使用DumpDebugTensor检查具体在那一层出错

如果要在多模型的情况下使用，建议通过Configure选项x86::ENGINE_CONF_DEBUG_DATA_DIR使不同模型的Tensor输出到不同的文件夹中（记得先新建文件夹）
不然模型之间的Tensor文件名字很容易冲突

**Comment by 111qqz** [comment]
感谢回答！我的所有模型的Tensor名字和大小确实是相同的
DumpDebugTensor这个功能是通过 ENGINE_CONF_TENSOR_DEBUG 来控制的吗？
我没有手动开启这个选项，在某个地方的文档看这个功能是默认关闭的

不过我看了下代码
https://github.com/openppl-public/ppl.nn/blob/master/include/ppl/nn/engines/x86/options.h#L43

似乎注释和代码出现了不一致的情况
![image](https://user-images.githubusercontent.com/30498101/219296752-c1be6f2f-1864-4189-9f4b-abd027bce9b6.png)

我手动关掉这个设置试试

**Comment by Alcanderian** [comment]
> 感谢回答！我的所有模型的Tensor名字和大小确实是相同的 DumpDebugTensor这个功能是通过 ENGINE_CONF_TENSOR_DEBUG 来控制的吗？ 我没有手动开启这个选项，在某个地方的文档看这个功能是默认关闭的
> 
> 不过我看了下代码 https://github.com/openppl-public/ppl.nn/blob/master/include/ppl/nn/engines/x86/options.h#L43
> 
> 似乎注释和代码出现了不一致的情况 ![image](https://user-images.githubusercontent.com/30498101/219296752-c1be6f2f-1864-4189-9f4b-abd027bce9b6.png)
> 
> 我手动关掉这个设置试试

这里的1指的使CONF的编号，并不是开关

**Comment by Alcanderian** [comment]
如果没有开启dump也出现了dump的文件的话，就要检查一下是否有内存越界把config改掉了

之前有多的图片反映到还有别的地方报错，恐怕是真的越界了

**Comment by 111qqz** [comment]
确实默认关闭了，眼滑看错了...
之前贴的另一张图是挂在ppt::common的 BufferInfo了。 我就提到pplcommon的仓库里了
那个错误应该是我没保证ppl::nn::engine的生命周期导致的,已经fix了
目前看fix后， core在  ppl::nn::x86::X86Kernel::DumpOutputTensors 的问题也没有继续出现了。

感谢解答！
