### ISSUE TITLE
获取模型推理结果（GetOutputs)耗时长

### ISSUE THREAD

**Issue by 111qqz** [openppl-public/ppl.nn#806]
What are the types of GPU/CPU you are using?
cpu

What's the operating system ppl.nn runs on?
CentOS Linux release 7.7.1908 (Core)

What's the compiler and its version?
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

Which version(commit id or tag) of ppl.nn is used?
[5b57da0](https://github.com/openppl-public/ppl.nn/commit/5b57da0b555ae2125c1626cc29aa314f1b61775b)

What are the commands used to build ppl.nn?
./build.sh -DPPLNN_USE_X86_64=ON

问题描述:

使用的是编译ppl.nn/tools/pplnn.py   出来的pplnn工具 ，命令为

```shell
./pplnn  --use-x86 --onnx-model model.onnx --mm-policy perf   --warmup-iterations 50  --min-profiling-seconds 10  --enable-profiling  --perf-with-io 

```

模型比较简单，本身的推理耗时大概只有3u
但是当设置"--perf-with-io"选项时，耗时会超过4u,具体来说，是在GetOutput  https://github.com/openppl-public/ppl.nn/blob/master/tools/pplnn.cc#L1097   导致耗时明显变长

我的模型只有单个float分数的输出

因此想问下，这部分耗时超过1u是正常的吗？ 有什么优化的办法吗？

**Comment by Alcanderian** [comment]
请问这里的3u, 4u, 1u的u代表什么呢？
GetOutput涉及了内存申请和内存拷贝，如果u指微秒那1u是正常的，实际场景中可以用过直接获取Tensor指针来获取数据，你可以根据自己的的要求来设计测试

**Comment by 111qqz** [comment]
对，u是us的意思。 感谢回答！
