### ISSUE TITLE
Does ppl.nn support fp16 or int8?

### ISSUE THREAD

**Issue by zerollzeng** [openppl-public/ppl.nn#9]
Just want to know if ppl.nn support half-precision or int8 inference.

Looking forward to your reply.

**Comment by openppl-public** [comment]
Currently PPLNN supports fp16 only.

> Just want to know if ppl.nn support half-precision or int8 inference.
> 
> Looking forward to your reply.

**Comment by zerollzeng** [comment]
Can we test the fp16 performance with pplnn-build/tools/pplnn?

**Comment by ltj2013** [comment]
> Can we test the fp16 performance with pplnn-build/tools/pplnn?



> Can we test the fp16 performance with pplnn-build/tools/pplnn?

Yes, you can test the fp16 performance with pplnn in tesla T4.

**Comment by openppl-public** [comment]
> Can we test the fp16 performance with pplnn-build/tools/pplnn?

Benchmark instructions are listed here: [Benchmark](https://github.com/openppl-public/ppl.nn/blob/master/docs/en/cuda-doc/benchmark_tool.md)（[中文版](https://github.com/openppl-public/ppl.nn/blob/master/docs/cn/cuda-doc/benchmark_tool.md)）

**Comment by zerollzeng** [comment]
Yeah, I read it before, eg running with:
```
./pplnn --onnx-model model.onnx --inputs input.bin --in-shapes 1_3_224_224 --dims 1_3_224_224 --warmuptimes 100 --runningtimes 100
``` 
will run the model on gpu with fp32 precision right? looks like we can not specify precision thought args.

**Comment by ltj2013** [comment]
> Yeah, I read it before, eg running with:
> 
> ```
> ./pplnn --onnx-model model.onnx --inputs input.bin --in-shapes 1_3_224_224 --dims 1_3_224_224 --warmuptimes 100 --runningtimes 100
> ```
> 
> will run the model on gpu with fp32 precision right? looks like we can not specify precision thought args.

 CUDA only support fp16 for conv and gemm op right now.  PPL will convert data type before excute. So the results will show the fp16 performance for cuda.
